var _yt_www={};(function(g){var window=this;var baa,caa,Ca,Fa,eb,kaa,fb,gb,ib,jb,pb,laa,qb,maa,Ab,naa,xb,Jb,$b,cc,gc,ic,Vc,waa,yaa,xaa,zaa,Aaa,id,ld,vd,Ad,Eaa,Faa,Daa,Gaa,ee,ge,fe,Jaa,Kaa,Laa,Maa,oe,qe,Oaa,re,se,ue,Paa,ye,le,ve,xe,ie,ne,je,pe,ze,Le,Oe,Re,Te,Ze,$e,vf,wf,Vaa,Ef,Ff,Waa,If,Mf,Kf,Jf,Xaa,Pf,Qf,Tf,Vf,Wf,Xf,$f,Zf,bg,Yf,cg,Rf,Uf,cba,dg,eg,dba,eba,kg,mg,og,vg,fba,Ag,yg,hba,Dg,Bg,Cg,Hg,gba,Fg,kba,jba,iba,Lg,Kg,Mg,Og,lba,mba,Pg,Qg,Vg,Zg,$g,ah,dh,eh,fh,sba,tba,Wg,Yg,Ug,rba,Xg,ih,jh,pa,aaa;
g.ba=function(a){return function(){return g.aa[a].apply(this,arguments)}};
g.ca=function(a){return void 0!==a};
g.m=function(a,b,c){a=a.split(".");c=c||g.da;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&g.ca(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}};
g.p=function(a,b){for(var c=a.split("."),d=b||g.da,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d};
g.ea=function(){};
g.fa=function(a){a.getInstance=function(){return a.Bc?a.Bc:a.Bc=new a}};
g.ga=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};
g.ha=function(a){return"array"==g.ga(a)};
g.ia=function(a){var b=g.ga(a);return"array"==b||"object"==b&&"number"==typeof a.length};
g.ka=function(a){return"string"==typeof a};
g.ma=function(a){return"number"==typeof a};
g.na=function(a){return"function"==g.ga(a)};
g.oa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};
g.qa=function(a){return a[pa]||(a[pa]=++aaa)};
baa=function(a,b,c){return a.call.apply(a.bind,arguments)};
caa=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};
g.q=function(a,b,c){g.q=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?baa:caa;return g.q.apply(null,arguments)};
g.r=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};
g.t=function(a,b){function c(){}
c.prototype=b.prototype;a.K=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,f){for(var k=Array(arguments.length-2),l=2;l<arguments.length;l++)k[l-2]=arguments[l];return b.prototype[c].apply(a,k)}};
g.ra=function(a){g.ra[" "](a);return a};
g.sa=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,g.sa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};
g.ta=function(a,b){return 0==a.lastIndexOf(b,0)};
g.ua=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c};
g.va=function(a){return(0,window.encodeURIComponent)(String(a))};
g.wa=function(a){return(0,window.decodeURIComponent)(a.replace(/\+/g," "))};
g.xa=function(a){if(!daa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(eaa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(faa,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(gaa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(haa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(iaa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(jaa,"&#0;"));return a};
g.za=function(a,b){return-1!=a.indexOf(b)};
g.Aa=function(a){return String(a).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08")};
g.Da=function(a,b){for(var c=0,d=(0,g.Ba)(String(a)).split("."),e=(0,g.Ba)(String(b)).split("."),f=Math.max(d.length,e.length),k=0;0==c&&k<f;k++){var l=d[k]||"",n=e[k]||"",u=RegExp("(\\d*)(\\D*)","g"),w=RegExp("(\\d*)(\\D*)","g");do{var H=u.exec(l)||["","",""],S=w.exec(n)||["","",""];if(0==H[0].length&&0==S[0].length)break;c=Ca(0==H[1].length?0:(0,window.parseInt)(H[1],10),0==S[1].length?0:(0,window.parseInt)(S[1],10))||Ca(0==H[2].length,0==S[2].length)||Ca(H[2],S[2])}while(0==c)}return c};
Ca=function(a,b){return a<b?-1:a>b?1:0};
g.Ea=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c)>>>0;return b};
Fa=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};
g.Ga=function(a){var b=g.ka(void 0)?g.Aa(void 0):"\\s";return a.replace(new RegExp("(^"+(b?"|["+b+"]+":"")+")([a-z])","g"),function(a,b,e){return b+e.toUpperCase()})};
g.Ia=function(a,b,c){b=g.Ha(a,b,c);return 0>b?null:g.ka(a)?a.charAt(b):a[b]};
g.Ha=function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return f;return-1};
g.La=function(a,b){return 0<=(0,g.Ka)(a,b)};
g.Na=function(a,b){var c=(0,g.Ka)(a,b),d;(d=0<=c)&&g.Ma(a,c);return d};
g.Ma=function(a,b){return 1==Array.prototype.splice.call(a,b,1).length};
g.Oa=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};
g.Pa=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(g.ia(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var k=0;k<f;k++)a[e+k]=d[k]}else a.push(d)}};
g.Qa=function(a){return function(){return a}};
g.Ra=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};
g.Sa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};
g.Ta=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};
g.Ua=function(a,b,c){for(var d in a)if(b.call(c,a[d],d,a))return d};
g.Va=function(a){for(var b in a)return!1;return!0};
g.Wa=function(a,b){b in a&&delete a[b]};
g.Xa=function(a,b,c){if(null!==a&&b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c};
g.Ya=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
g.$a=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Za.length;f++)c=Za[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
g.bb=function(a){return g.za(g.ab,a)};
g.cb=function(){return g.bb("Trident")||g.bb("MSIE")};
g.db=function(){return(g.bb("Chrome")||g.bb("CriOS"))&&!g.bb("Edge")};
eb=function(a){g.da.setTimeout(function(){throw a;},0)};
kaa=function(){var a=g.da.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!g.bb("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=(0,g.q)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);
b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});
if("undefined"!==typeof a&&!g.cb()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(g.ca(c.next)){c=c.next;var a=c.Ip;c.Ip=null;a()}};
return function(a){d.next={Ip:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT");
b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};
window.document.documentElement.appendChild(b)}:function(a){g.da.setTimeout(a,0)}};
fb=function(a,b,c){this.F=c;this.B=a;this.D=b;this.C=0;this.A=null};
gb=function(a,b){a.D(b);a.C<a.F&&(a.C++,b.next=a.A,a.A=b)};
ib=function(){this.C=this.A=null};
jb=function(){this.next=this.scope=this.ye=null};
pb=function(a,b){kb||laa();lb||(kb(),lb=!0);var c=nb,d=ob.get();d.set(a,b);c.C?c.C.next=d:c.A=d;c.C=d};
laa=function(){if(g.da.Promise&&g.da.Promise.resolve){var a=g.da.Promise.resolve(void 0);kb=function(){a.then(qb)}}else kb=function(){var a=qb;
!g.na(g.da.setImmediate)||g.da.Window&&g.da.Window.prototype&&!g.bb("Edge")&&g.da.Window.prototype.setImmediate==g.da.setImmediate?(rb||(rb=kaa()),rb(a)):g.da.setImmediate(a)}};
qb=function(){for(var a=null;a=nb.remove();){try{a.ye.call(a.scope)}catch(b){eb(b)}gb(ob,a)}lb=!1};
g.sb=function(){this.Td=this.Td;this.Kb=this.Kb};
g.vb=function(a,b){g.tb(a,g.r(g.ub,b))};
g.tb=function(a,b){a.Td?b.call(void 0):(a.Kb||(a.Kb=[]),a.Kb.push(g.ca(void 0)?(0,g.q)(b,void 0):b))};
g.ub=function(a){a&&"function"==typeof a.dispose&&a.dispose()};
g.wb=function(a){g.sb.call(this);this.D=1;this.C=[];this.B=0;this.A=[];this.yd={};this.F=!!a};
maa=function(a,b,c){pb(function(){a.apply(b,c)})};
g.zb=function(a){xb(g.yb,arguments)};
g.v=function(a,b){return a in g.yb?g.yb[a]:b};
g.Bb=function(a,b){g.na(a)&&(a=Ab(a));return window.setTimeout(a,b)};
g.Cb=function(a,b){g.na(a)&&(a=Ab(a));return window.setInterval(a,b)};
g.Db=function(a){window.clearTimeout(a)};
g.Eb=function(a){window.clearInterval(a)};
Ab=function(a){return a&&window.yterr?function(){try{return a.apply(this,arguments)}catch(b){throw g.Fb(b),b;}}:a};
g.Fb=function(a,b,c,d,e){var f=g.p("yt.logging.errors.log");f?f(a,b,c,d,e):(f=g.v("ERRORS",[]),f.push([a,b,c,d,e]),g.zb("ERRORS",f))};
naa=function(a,b,c,d,e){var f=!1;if(g.yb.Vo&&g.yb.Vo.log_window_onerror_fraction&&Math.random()<g.yb.Vo.log_window_onerror_fraction)f=!0;else for(var k=window.document.getElementsByTagName("script"),l=0,n=k.length;l<n;l++)if(0<k[l].src.indexOf("/debug-")){f=!0;break}f&&(e||(e=Error(),e.message=a,e.fileName=b,e.lineNumber=c,(0,window.isNaN)(d)||(e.columnNumber=d)),g.Fb(e))};
g.Hb=function(a){return a in g.Gb};
g.Ib=function(a,b,c){var d=b||{};if(a=a in g.Gb?g.Gb[a]:c)for(var e in d)a=a.replace(new RegExp("\\$"+e,"gi"),function(){return d[e]});
return a};
xb=function(a,b){if(1<b.length){var c=b[0];a[c]=b[1]}else{var d=b[0];for(c in d)a[c]=d[c]}};
g.x=function(a,b,c){var d=Jb();if(d){var e=d.subscribe(a,function(){if(!Kb||Kb!=e){var d=arguments,k;k=function(){Lb[e]&&b.apply(c||window,d)};
try{Mb[a]?k():g.Bb(k,0)}catch(l){g.Fb(l)}}},c);
Lb[e]=!0;Nb[a]||(Nb[a]=[]);Nb[a].push(e);return e}return 0};
g.Ob=function(a){var b=Jb();b&&("number"==typeof a?a=[a]:"string"==typeof a&&(a=[(0,window.parseInt)(a,10)]),(0,g.y)(a,function(a){b.unsubscribeByKey(a);delete Lb[a]}))};
g.z=function(a,b){var c=Jb();return c?c.publish.apply(c,arguments):!1};
g.Pb=function(a,b){Mb[a]=!0;var c=Jb(),c=c?c.publish.apply(c,arguments):!1;Mb[a]=!1;return c};
Jb=function(){return g.p("yt.pubsub.instance_")};
g.Qb=function(){return!!g.p("yt.scheduler.instance")};
g.Rb=function(a,b){(0,window.isNaN)(b)&&(b=void 0);var c=g.p("yt.scheduler.instance.addJob");return c?c(a,0,b):void 0===b?(a(),window.NaN):g.Bb(a,b||0)};
g.Sb=function(a,b){return g.Rb(a,b)};
g.Tb=function(a){if(!(0,window.isNaN)(a)){var b=g.p("yt.scheduler.instance.cancelJob");b?b(a):g.Db(a)}};
g.Ub=function(a){for(var b=0,c=a.length;b<c;b++)g.Tb(a[b])};
g.Wb=function(a,b,c,d,e){this.name=a;this.deps=b||[];this.page=c||"";this.G=d?Ab(d):null;this.F=e?Ab(e):null;this.D=[];this.A=this.C=0};
g.Xb=function(a){g.Tb(a.C);a.C=g.Sb((0,g.q)(a.init,a))};
g.ac=function(a){a.name in Yb&&$b(a.name);Yb[a.name]={reqs:[],disable:(0,g.q)(a.disable,a)};(0,g.y)(a.deps,function(b){if(!(b in Yb))throw Error("Module "+b+" required by "+a.name);Yb[b].reqs.push(a.name)});
a.enable()};
$b=function(a){if(a in Yb){var b=Yb[a];(0,g.y)(b.reqs,function(a){$b(a)});
try{b.disable()}catch(c){}delete Yb[a]}};
cc=function(){this.A="";this.C=bc};
g.dc=function(a){return a instanceof cc&&a.constructor===cc&&a.C===bc?a.A:"type_error:Const"};
g.ec=function(a){var b=new cc;b.A=a;return b};
gc=function(){this.A="";this.C=fc};
g.hc=function(a){if(a instanceof gc&&a.constructor===gc&&a.C===fc)return a.A;g.ga(a);return"type_error:SafeStyle"};
ic=function(a){var b=new gc;b.A=a;return b};
g.jc=function(a){var b="",c;for(c in a){if(!/^[-_a-zA-Z0-9]+$/.test(c))throw Error("Name allows only [-_a-zA-Z0-9], got: "+c);var d=a[c];if(null!=d){if(d instanceof cc)d=g.dc(d);else if(oaa.test(d)){for(var e=!0,f=!0,k=0;k<d.length;k++){var l=d.charAt(k);"'"==l&&f?e=!e:'"'==l&&e&&(f=!f)}e&&f||(d="zClosurez")}else d="zClosurez";b+=c+":"+d+";"}}return b?ic(b):paa};
g.lc=function(){this.A="";this.C=kc};
g.mc=function(a){if(a instanceof g.lc&&a.constructor===g.lc&&a.C===kc)return a.A;g.ga(a);return"type_error:SafeUrl"};
g.oc=function(a){if(a instanceof g.lc)return a;a=a.Tf?a.Ve():String(a);qaa.test(a)||(a="about:invalid#zClosurez");return g.nc(a)};
g.nc=function(a){var b=new g.lc;b.A=a;return b};
g.qc=function(){this.A="";this.C=pc};
g.rc=function(a){if(a instanceof g.qc&&a.constructor===g.qc&&a.C===pc)return a.A;g.ga(a);return"type_error:TrustedResourceUrl"};
g.tc=function(){this.A="";this.B=sc;this.C=null};
g.uc=function(a){if(a instanceof g.tc&&a.constructor===g.tc&&a.B===sc)return a.A;g.ga(a);return"type_error:SafeHtml"};
g.wc=function(a){if(a instanceof g.tc)return a;var b=null;a.Gm&&(b=a.Bg());a=g.xa(a.Tf?a.Ve():String(a));return g.vc(a,b)};
g.zc=function(a,b,c){if(!xc.test(a))throw Error("Invalid tag name <"+a+">.");if(a.toUpperCase()in raa)throw Error("Tag name <"+a+"> is not allowed for SafeHtml.");return g.yc(a,b,c)};
g.Ac=function(a){function b(a){g.ha(a)?(0,g.y)(a,b):(a=g.wc(a),d+=g.uc(a),a=a.Bg(),0==c?c=a:0!=a&&c!=a&&(c=null))}
var c=0,d="";(0,g.y)(arguments,b);return g.vc(d,c)};
g.vc=function(a,b){var c=new g.tc;c.A=a;c.C=b;return c};
g.yc=function(a,b,c){var d=null,e,f="";if(b)for(e in b){if(!xc.test(e))throw Error('Invalid attribute name "'+e+'".');var k=b[e];if(null!=k){var l,n=a;l=e;if(k instanceof cc)k=g.dc(k);else if("style"==l.toLowerCase()){if(!g.oa(k))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof k+" given: "+k);k instanceof gc||(k=g.jc(k));k=g.hc(k)}else{if(/^on/i.test(l))throw Error('Attribute "'+l+'" requires goog.string.Const value, "'+k+'" given.');if(l.toLowerCase()in
saa)if(k instanceof g.qc)k=g.rc(k);else if(k instanceof g.lc)k=g.mc(k);else if(g.ka(k))k=g.oc(k).Ve();else throw Error('Attribute "'+l+'" on tag "'+n+'" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+k+'" given.');}k.Tf&&(k=k.Ve());l=l+'="'+g.xa(String(k))+'"';f+=" "+l}}e="<"+a+f;null!=c?g.ha(c)||(c=[c]):c=[];!0===taa[a.toLowerCase()]?e+=">":(d=g.Ac(c),e+=">"+g.uc(d)+"</"+a+">",d=d.Bg());(a=b&&b.dir)&&(/^(ltr|rtl|auto)$/i.test(a)?d=0:d=null);return g.vc(e,d)};
g.Bc=function(a,b){a.innerHTML=g.uc(b)};
g.Cc=function(a,b){var c;c=b instanceof g.lc?b:g.oc(b);a.href=g.mc(c)};
g.A=function(a,b){return a?a.dataset?a.dataset[g.Dc(b)]:a.getAttribute("data-"+b):null};
g.Ec=function(a,b){return a?a.dataset?g.Dc(b)in a.dataset:a.hasAttribute?!!a.hasAttribute("data-"+b):!!a.getAttribute("data-"+b):!1};
g.Dc=function(a){return Fc[a]||(Fc[a]=String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()}))};
g.Hc=function(a,b){var c=g.Gc(a);window.spf.script.load(a,c,b)};
g.Ic=function(a,b){var c=g.Gc(a);window.spf.script.ignore(c,b)};
g.Gc=function(a){var b="";if(a){var c=a.indexOf("jsbin/"),d=a.lastIndexOf(".js"),e=c+6;-1<c&&-1<d&&d>e&&(b=a.substring(e,d),b=b.replace(uaa,""),b=b.replace(vaa,""),b=b.replace("debug-",""),b=b.replace("tracing-",""))}return b};
g.Jc=function(a){return g.v("EXPERIMENT_FLAGS",{})[a]};
g.Kc=function(a,b){g.dc(a);g.dc(a);return g.vc(b,null)};
g.Lc=function(a){return eval("("+a+")")};
g.Mc=function(a,b,c,d,e,f,k){var l="";a&&(l+=a+":");c&&(l+="//",b&&(l+=b+"@"),l+=c,d&&(l+=":"+d));e&&(l+=e);f&&(l+="?"+f);k&&(l+="#"+k);return l};
g.Nc=function(a){return a?(0,window.decodeURI)(a):a};
g.Pc=function(a,b){return b.match(g.Oc)[a]||null};
g.Qc=function(a){return g.Nc(g.Pc(3,a))};
g.Rc=function(a){a=a.match(g.Oc);return g.Mc(null,null,null,null,a[5],a[6],a[7])};
g.Sc=function(a){var b=a.indexOf("#");return 0>b?a:a.substr(0,b)};
g.Tc=function(a){if(a[1]){var b=a[0],c=b.indexOf("#");0<=c&&(a.push(b.substr(c)),a[0]=b=b.substr(0,c));c=b.indexOf("?");0>c?a[1]="?":c==b.length-1&&(a[1]=void 0)}return a.join("")};
g.Uc=function(a,b,c){if(g.ha(b))for(var d=0;d<b.length;d++)g.Uc(a,String(b[d]),c);else null!=b&&c.push("&",a,""===b?"":"=",g.va(b))};
Vc=function(a,b){for(var c in b)g.Uc(c,b[c],a);return a};
g.Wc=function(a){a=Vc([],a);a[0]="";return a.join("")};
g.Xc=function(a,b){return g.Tc(Vc([a],b))};
g.Yc=function(a){"?"==a.charAt(0)&&(a=a.substr(1));a=a.split("&");for(var b={},c=0,d=a.length;c<d;c++){var e=a[c].split("=");if(1==e.length&&e[0]||2==e.length){var f=g.wa(e[0]||""),e=g.wa(e[1]||"");f in b?g.ha(b[f])?g.Pa(b[f],e):b[f]=[b[f],e]:b[f]=e}}return b};
g.Zc=function(a,b){var c,d=b||{},e=a.split("#",2);c=e[0];var e=1<e.length?"#"+e[1]:"",f=c.split("?",2);c=f[0];var f=g.Yc(f[1]||""),k;for(k in d)f[k]=d[k];return g.Xc(c,f)+e};
waa=function(a){a=g.$c(a);return g.ad(a)||(null===a?!1:"google"==a[1]?!0:"google"==a[2]?"au"==a[0]&&"com"==a[1]?!0:"uk"==a[0]&&"co"==a[1]?!0:!1:!1)};
g.ad=function(a){return null===a?!1:"com"==a[0]&&a[1].match(/^youtube(?:-nocookie)?$/)?!0:!1};
g.$c=function(a){a=g.Qc(a);return null===a?null:a.split(".").reverse()};
g.bd=function(a){return a&&"status"in a?a.status:-1};
g.cd=function(a){switch(g.bd(a)){case 200:case 201:case 202:case 203:case 204:case 205:case 206:case 304:return!0;default:return!1}};
yaa=function(a,b,c,d,e,f,k){function l(){4==(n&&"readyState"in n?n.readyState:0)&&b&&Ab(b)(n)}
var n=dd&&dd();if(!("open"in n))return null;"onloadend"in n?n.addEventListener("loadend",l,!1):n.onreadystatechange=l;c=(c||"GET").toUpperCase();d=d||"";n.open(c,a,!0);f&&(n.responseType=f);k&&(n.withCredentials=!0);f="POST"==c;if(e=xaa(a,e))for(var u in e)n.setRequestHeader(u,e[u]),"content-type"==u.toLowerCase()&&(f=!1);f&&n.setRequestHeader("Content-Type","application/x-www-form-urlencoded");n.send(d);return n};
xaa=function(a,b){b=b||{};var c;c||(c=window.location.href);var d=g.Pc(1,a),e=g.Qc(a);d&&e?(d=c,c=a.match(g.Oc),d=d.match(g.Oc),c=c[3]==d[3]&&c[1]==d[1]&&c[4]==d[4]):c=e?g.Qc(c)==e&&(Number(g.Pc(4,c))||null)==(Number(g.Pc(4,a))||null):!0;for(var f in ed){if((e=d=g.v(ed[f]))&&!(e=c)){var e=f,k=g.v("CORS_HEADER_WHITELIST")||{},l=g.Qc(a);e=l?(k=k[l])?g.La(k,e):!1:!0}e&&(b[f]=d)}return b};
g.fd=function(a,b){b.method="POST";b.ea||(b.ea={});return g.B(a,b)};
zaa=function(a,b){var c=g.v("XSRF_FIELD_NAME",void 0),d;b.headers&&(d=b.headers["Content-Type"]);return!b.Wy&&(!g.Qc(a)||b.withCredentials||g.Qc(a)==window.document.location.hostname)&&"POST"==b.method&&(!d||"application/x-www-form-urlencoded"==d)&&!(b.ea&&b.ea[c])};
g.B=function(a,b){var c=b.format||"JSON";b.JU&&(a=window.document.location.protocol+"//"+window.document.location.hostname+(window.document.location.port?":"+window.document.location.port:"")+a);var d=g.v("XSRF_FIELD_NAME",void 0),e=g.v("XSRF_TOKEN",void 0),f=b.ka;f&&(f[d]&&delete f[d],a=g.Zc(a,f));var k=b.postBody||"",f=b.ea;zaa(a,b)&&(f||(f={}),f[d]=e);f&&g.ka(k)&&(d=g.Yc(k),g.$a(d,f),k=b.Ju&&"JSON"==b.Ju?JSON.stringify(d):g.Wc(d));var l=!1,n,u=yaa(a,function(a){if(!l){l=!0;n&&g.Db(n);var d=g.cd(a),
e=null;if(d||400<=a.status&&500>a.status)e=Aaa(c,a,b.rb);if(d)a:{switch(c){case "XML":d=0==(0,window.parseInt)(e&&e.return_code,10);break a;case "RAW":d=!0;break a}d=!!e}var e=e||{},f=b.context||g.da;d?b.X&&b.X.call(f,a,e):b.onError&&b.onError.call(f,a,e);b.Ya&&b.Ya.call(f,a,e)}},b.method,k,b.headers,b.responseType,b.withCredentials);
b.Gc&&0<b.timeout&&(n=g.Bb(function(){l||(l=!0,u.abort(),g.Db(n),b.Gc.call(b.context||g.da,u))},b.timeout));
return u};
Aaa=function(a,b,c){var d=null;switch(a){case "JSON":a=b.responseText;b=b.getResponseHeader("Content-Type")||"";a&&0<=b.indexOf("json")&&(d=g.Lc(a));break;case "XML":if(b=(b=b.responseXML)?g.gd(b):null)d={},(0,g.y)(b.getElementsByTagName("*"),function(a){d[a.tagName]=g.hd(a)})}c&&id(d);
return d};
id=function(a){if(g.oa(a))for(var b in a)"html_content"==b||g.ua(b,"_html")?a[b]=g.Kc(g.ec("HTML that is escaped and sanitized server-side and passed through yt.net.ajax"),a[b]):id(a[b])};
g.gd=function(a){return a?(a=("responseXML"in a?a.responseXML:a).getElementsByTagName("root"))&&0<a.length?a[0]:null:null};
g.hd=function(a){var b="";(0,g.y)(a.childNodes,function(a){b+=a.nodeValue});
return b};
g.jd=function(){return{apiaryHost:g.v("APIARY_HOST",void 0),sp:g.v("APIARY_HOST_FIRSTPARTY",void 0),gapiHintOverride:g.v("GAPI_HINT_OVERRIDE"),gapiHintParams:g.v("GAPI_HINT_PARAMS",void 0),innertubeApiKey:g.v("INNERTUBE_API_KEY",void 0),innertubeApiVersion:g.v("INNERTUBE_API_VERSION",void 0),JD:g.v("INNERTUBE_CONTEXT_CLIENT_NAME","WEB"),innertubeContextClientVersion:g.v("INNERTUBE_CONTEXT_CLIENT_VERSION",void 0),LD:g.v("INNERTUBE_CONTEXT_HL",void 0),KD:g.v("INNERTUBE_CONTEXT_GL",void 0),zO:g.v("XHR_APIARY_HOST",
void 0)}};
g.kd=function(a){a={client:{hl:a.LD,gl:a.KD,clientName:a.JD,clientVersion:a.innertubeContextClientVersion}};g.v("DELEGATED_SESSION_ID")&&(a.user={onBehalfOfUser:g.v("DELEGATED_SESSION_ID")});return a};
ld=function(){this.A=g.jd()};
g.md=function(a,b,c){this.A=a;this.B=b;this.C=c};
g.rd=function(a,b){g.nd[a.endpoint]=g.nd[a.endpoint]||[];var c=g.nd[a.endpoint];c.push(a.Eb);od[a.endpoint]=b;20<=c.length?g.pd():g.qd()};
g.pd=function(){g.Db(g.sd);if(!g.Va(g.nd)){for(var a in g.nd){var b=g.td[a];if(!b){b=od[a];if(!b)continue;b=new b;g.td[a]=b}var c=b.C();c.requestTimeMs=Math.round(ud());c[Baa[a]]=g.nd[a];b.B(a,c,{});delete g.nd[a]}g.Va(g.nd)||g.qd()}};
g.qd=function(){g.Db(g.sd);g.sd=g.Bb(g.pd,g.v("VISIBILITY_TIMEOUT",1E4))};
vd=function(a,b,c){var d={};d.eventTimeMs=Math.round(c||ud());d[a]=b;g.rd({endpoint:"log_event",Eb:d},ld)};
g.wd=function(){var a=g.v("client-screen-nonce",void 0);a||(a=g.v("EVENT_ID",void 0));return a};
g.xd=function(a,b){this.x=g.ca(a)?a:0;this.y=g.ca(b)?b:0};
g.yd=function(a,b){this.width=a;this.height=b};
g.zd=function(){return g.bb("iPhone")&&!g.bb("iPod")&&!g.bb("iPad")};
Ad=function(){var a=g.da.document;return a?a.documentMode:void 0};
g.Dd=function(a){return Bd[a]||(Bd[a]=0<=g.Da(g.Cd,a))};
g.Fd=function(a){return Number(g.Ed)>=a};
g.C=function(a){return g.ka(a)?window.document.getElementById(a):a};
g.Gd=function(a){return g.ka(a)?window.document.getElementById(a):a};
g.D=function(a,b){var c=b||window.document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:c.querySelectorAll&&c.querySelector?d=c.querySelector("."+a):d=g.Hd(window.document,"*",a,b)[0];return d||null};
g.Hd=function(a,b,c,d){a=d||a;b=b&&"*"!=b?b.toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,k;k=a[f];f++)b==k.nodeName&&(d[e++]=k);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;k=a[f];f++)b=k.className,"function"==typeof b.split&&g.La(b.split(/\s+/),c)&&(d[e++]=k);d.length=e;return d}return a};
g.Jd=function(a,b){g.Sa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:Id.hasOwnProperty(d)?a.setAttribute(Id[d],b):g.ta(d,"aria-")||g.ta(d,"data-")?a.setAttribute(d,b):a[d]=b})};
g.Ld=function(a){return g.Kd(a||window)};
g.Kd=function(a){a=a.document;a=g.Md(a)?a.documentElement:a.body;return new g.yd(a.clientWidth,a.clientHeight)};
g.Od=function(a){var b=g.Nd(a);a=a.parentWindow||a.defaultView;return g.E&&g.Dd("10")&&a.pageYOffset!=b.scrollTop?new g.xd(b.scrollLeft,b.scrollTop):new g.xd(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};
g.Nd=function(a){return a.scrollingElement?a.scrollingElement:!g.Pd&&g.Md(a)?a.documentElement:a.body||a.documentElement};
g.Rd=function(a,b,c){return g.Qd(window.document,arguments)};
g.Qd=function(a,b){var c=b[0],d=b[1];if(!Caa&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',g.xa(d.name),'"');if(d.type){c.push(' type="',g.xa(d.type),'"');var e={};g.$a(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(g.ka(d)?c.className=d:g.ha(d)?c.className=d.join(" "):g.Jd(c,d));2<b.length&&g.Sd(a,c,b,2);return c};
g.Sd=function(a,b,c,d){function e(c){c&&b.appendChild(g.ka(c)?a.createTextNode(c):c)}
for(;d<c.length;d++){var f=c[d];!g.ia(f)||g.oa(f)&&0<f.nodeType?e(f):(0,g.y)(Daa(f)?g.Oa(f):f,e)}};
g.Md=function(a){return"CSS1Compat"==a.compatMode};
g.Td=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};
g.Ud=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};
g.Vd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};
Eaa=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
Faa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};
g.Wd=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
Daa=function(a){if(a&&"number"==typeof a.length){if(g.oa(a))return"function"==typeof a.item||"string"==typeof a.item;if(g.na(a))return"function"==typeof a.item}return!1};
g.Xd=function(a,b,c,d){c||(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null};
g.Yd=function(a,b,c){a&&(c&&(c=g.ab,c=!(c&&0<=c.toLowerCase().indexOf("cobalt"))),c?a&&(a=g.Rd("iframe",{src:'javascript:"data:text/html,<body><img src=\\"'+a+'\\"></body>"',style:"display:none"}),g.Wd(a).body.appendChild(a)):Gaa(a,b))};
g.Zd=function(a){try{window.navigator&&window.navigator.sendBeacon&&window.navigator.sendBeacon(a,"")||g.Yd(a,void 0)}catch(b){g.Yd(a,void 0)}};
Gaa=function(a,b){var c=new window.Image,d=""+Haa++;$d[d]=c;c.onload=c.onerror=function(){b&&$d[d]&&b();delete $d[d]};
c.src=a};
g.ae=function(a,b){this.version=a;this.args=b};
g.be=function(a,b){this.topic=a;this.Bf=b};
g.de=function(a,b){var c=g.ce();return c?c.publish.call(c,a.toString(),a,b):!1};
g.ce=function(){return g.p("yt.pubsub2.instance_")};
ee=function(a){g.ae.call(this,1,arguments)};
ge=function(a){var b=a||window;if(!(b.performance&&b.performance.timing&&b.performance.getEntriesByType))return{Kk:0,dw:0};a=g.Ld(b);for(var c=[],d=b.document.getElementsByTagName("*"),e=0,f=d.length;e<f;e++){var k=d[e];if("IMG"==k.tagName||"IFRAME"==k.tagName){var l=fe(k,k.src,a);if(l){if("IFRAME"==k.tagName){var n;try{n=ge(k.contentWindow).Kk}catch(u){n=0}0<n&&(l.timing=n)}c.push(l)}}(l=b.getComputedStyle(k)["background-image"])&&(l=Iaa.exec(l))&&1<l.length&&(l=fe(k,l[1],a))&&c.push(l)}n=b.performance.getEntriesByType("resource");
k=b.performance.getEntriesByType("mark");d={};e=0;for(f=n.length;e<f;e++)l=n[e],d[l.name]=l.responseEnd;e=0;for(f=k.length;e<f;e++)l=k[e],"mark_iframe_loaded: "==l.name.slice(0,20)&&(d[l.name.slice(20)]=l.startTime);e=0;for(f=c.length;e<f;e++)k=c[e],k.timing||(k.timing=d[k.url]||0);b=Jaa(b,n);a=Kaa(b,a,c);k=c=0;if(a.length)for(d=n=0,e=a.length;d<e;d++)f=a[d],k=f.timing-k,0<k&&1>n&&(c+=(1-n)*k),k=f.timing,n=f.progress;return{Kk:Math.round(c||b),dw:k}};
fe=function(a,b,c){if(b&&a.getBoundingClientRect){var d=a.getBoundingClientRect();a=Math.max(d.top,0);var e=Math.min(d.right,c.width);c=Math.min(d.bottom,c.height);d=Math.max(d.left,0);if(c>a&&e>d)return new Laa(a,e,c,d,b)}return null};
Jaa=function(a,b){var c,d=a.performance.timing.navigationStart;if("msFirstPaint"in a.performance.timing)c=a.performance.timing.A-d;else if("chrome"in a&&"loadTimes"in a.chrome){var e=a.chrome.loadTimes(),f=e.firstPaintTime;if(0<f){var k=e.startLoadTime;"requestTime"in e&&(k=e.requestTime);f>=k&&(c=1E3*(f-k))}}if(void 0===c||0>c||12E4<c){c=a.performance.timing.responseStart-d;for(var l={},d=a.document.getElementsByTagName("head")[0].children,e=0,f=d.length;e<f;e++)k=d[e],"SCRIPT"==k.tagName&&k.src&&
!k.async?l[k.src]=!0:"LINK"==k.tagName&&"stylesheet"==k.rel&&k.href&&(l[k.href]=!0);b.some(function(a){if(!l[a.name]||"script"!=a.initiatorType&&"link"!=a.initiatorType)return!0;a=a.responseEnd;if(void 0===c||a>c)c=a})}return Math.max(c,0)||0};
Kaa=function(a,b,c){for(var d={0:0},e=0,f=0,k=c.length;f<k;f++){var l=c[f],n=a;l.timing>a&&(n=l.timing);d[n]||(d[n]=0);l=(l.A-l.D)*(l.B-l.C);d[n]+=l;e+=l}f=b.width*b.height;0<f&&(f=.1*Math.max(f-e,0),a in d||(d[a]=0),d[a]+=f,e+=f);a=[];if(e){for(var u in d)b=new Maa((0,window.parseFloat)(u),d[u]),a.push(b);a.sort(function(a,b){return a.timing-b.timing});
f=d=0;for(k=a.length;f<k;f++)b=a[f],d+=b.area,b.progress=d/e}return a};
Laa=function(a,b,c,d,e){this.A=c;this.C=d;this.B=b;this.D=a;this.url=e};
Maa=function(a,b){this.area=b;this.timing=a};
g.me=function(a,b,c){b||he(a);ie(c)[a]=b||ud();if(g.Jc("csi_on_gel")){var d=je(c).nonce;if(!d){var e;a:{if(window.crypto&&window.crypto.getRandomValues)try{var f=Array(16),k=new window.Uint8Array(16);window.crypto.getRandomValues(k);for(d=0;d<f.length;d++)f[d]=k[d];e=f;break a}catch(l){}e=Array(16);for(f=0;16>f;f++){k=(0,g.F)();for(d=0;d<k%23;d++)e[f]=Math.random();e[f]=Math.floor(256*Math.random())}if(ke)for(f=1,k=0;k<ke.length;k++)e[f%16]=e[f%16]^e[(f-1)%16]/4^ke.charCodeAt(k),f++}f=[];for(k=0;k<
e.length;k++)f.push("abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-_".charAt(e[k]&63));d=f.join("");je(c).nonce=d}c=d;"_start"==a?vd("latencyActionBaselined",{clientActionNonce:c},b):vd("latencyActionTicked",{tickName:a,clientActionNonce:c},b)}else le(!1,c)};
oe=function(a,b){ne(void 0).yt_sts=a;g.me("_start",b,void 0)};
qe=function(a){pe(a);Naa();g.m("yt.timing.pingSent_",!1,void 0)};
Oaa=function(){var a=g.wd();a&&(ne(void 0).csn=a)};
re=function(a){a=ie(a);if(a.aft)return a.aft;for(var b=g.v("TIMING_AFT_KEYS",["ol"]),c=b.length,d=0;d<c;d++){var e=a[b[d]];if(e)return e}return window.NaN};
se=function(a,b){var c=b||je(void 0).span,d;d=a.redirectEnd-a.redirectStart;0<d&&(c.rtime_=d);d=a.domainLookupEnd-a.domainLookupStart;0<d&&(c.dns_=d);d=a.connectEnd-a.connectStart;0<d&&(c.tcp_=d);d=a.connectEnd-a.secureConnectionStart;a.secureConnectionStart>=a.navigationStart&&0<d&&(c.stcp_=d);d=a.responseStart-a.requestStart;0<d&&(c.req_=d);d=a.responseEnd-a.responseStart;0<d&&(c.rcv_=d)};
ue=function(a){return Math.round(te.timing.navigationStart+a)};
Paa=function(a){var b=window.location.protocol,c=te.getEntriesByType("resource"),d=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.googleapis.com/css?family=")})[0],c=c.filter(function(a){return 0==a.name.indexOf(b+"//fonts.gstatic.com/s/")}).reduce(function(a,b){return b.duration>a.duration?b:a},{duration:0});
d&&0<d.startTime&&0<d.responseEnd&&(a.wfcs=ue(d.startTime),a.wfce=ue(d.responseEnd));c&&0<c.startTime&&0<c.responseEnd&&(a.wffs=ue(c.startTime),a.wffe=ue(c.responseEnd))};
ye=function(a){var b=ie(a),c=je(a).span,d=ne(a),e=g.p("yt.timing.reportbuilder_");if(e){if(e=e(b,c,d,a))ve(e),qe(a)}else{var f=g.v("TIMING_ACTION",void 0),k=g.v("CSI_SERVICE_NAME","youtube"),e={v:2,s:k,action:f};if(te.now&&te.timing){var l=te.timing.navigationStart+te.now(),l=Math.round((0,g.F)()-l);d.yt_hrd=l}var l=g.v("TIMING_INFO",{}),n;for(n in l)d[n]=l[n];n=d.srt;delete d.srt;var u;void 0===b.srt&&(n||0===n||(u=te.timing||{},n=Math.max(0,u.responseStart-u.navigationStart),(0,window.isNaN)(n)&&
d.pt&&(n=d.pt)),n||0===n)&&(d.srt=Math.round(n));d.h5jse&&(l=window.location.protocol+g.p("ytplayer.config.assets.js"),(l=te.getEntriesByName?te.getEntriesByName(l)[0]:null)?d.h5jse=Math.round(d.h5jse-l.responseEnd):delete d.h5jse);b.aft=re(a);l=b._start;if("cold"==d.yt_lt){u||(u=te.timing||{});var w;a:if(w=u,w.msFirstPaint)w=Math.max(0,w.msFirstPaint);else{var H=window.chrome;if(H&&(H=H.loadTimes,g.na(H))){var H=H(),S=1E3*Math.min(H.requestTime||window.Infinity,H.startLoadTime||window.Infinity),
S=window.Infinity===S?0:w.navigationStart-S;w=Math.max(0,Math.round(1E3*H.firstPaintTime+S)||0);break a}w=0}0<w&&w>l&&(b.fpt=w);se(u,c);te.getEntriesByType&&Paa(b);(u=g.v("SPEEDINDEX_FOR_ACTIONS",void 0))&&-1<u.indexOf(f)&&(f=ud(),u=ge(),w=ud(),0<u.Kk&&(d.si=u.Kk,b.vsc=ue(u.dw),b.sics=f,b.sice=w));f=[];if(window.document.querySelector&&te&&te.getEntriesByName)for(var Z in we)if(u=window.document.querySelector(Z))w="",H=u.nodeName,"SCRIPT"==H?w=u.src:"LINK"==H&&(w=u.href),w&&(u=te.getEntriesByName(w))&&
u[0]&&f.push(we[Z]+"."+Math.round(u[0].duration));f.length&&(d.rs=f.join(","))}u=ie(a);Z=u.pbr;f=u.vc;u=u.pbs;Z&&f&&u&&Z<f&&f<u&&1==ne(a).yt_vis&&"youtube"==k&&(ne(a).yt_lt="hot_bg",k=b.vc,Z=b.pbs,delete b.aft,d.aft=Math.round(Z-k));(k=g.v("PREVIOUS_ACTION"))&&(d.pa=k);d.p=g.v("CLIENT_PROTOCOL")||"unknown";d.t=g.v("CLIENT_TRANSPORT")||"unknown";window.navigator&&window.navigator.sendBeacon&&(d.ba=1);for(var la in d)"_"!=la.charAt(0)&&(e[la]=d[la]);b.ps=ud();d={};la=[];for(var ya in b)"_"!=ya.charAt(0)&&
(w=Math.round(b[ya]-l),g.Jc("enable_negative_ticks")||(w=Math.max(w,0)),d[ya]=w,la.push(ya+"."+w));e.rt=la.join(",");b=e;ya=[];for(var Ja in c)"_"!=Ja.charAt(0)&&ya.push(Ja+"."+Math.round(c[Ja]));b.it=ya.join(",");(Ja=g.p("ytdebug.logTiming"))&&Ja(e,d,c);qe(a);g.v("EXP_DEFER_CSI_PING")?(xe(),g.m("yt.timing.deferredPingArgs_",e,void 0),a=g.Bb(xe,0),g.m("yt.timing.deferredPingTimer_",a,void 0)):ve(e);g.de(Qaa,new ee(d.aft+(n||0)))}};
le=function(a,b){var c=g.v("TIMING_ACTION",void 0),d=ie(b);if(g.p("yt.timing.ready_")&&c&&d._start&&re(b)){var c=!0,e=g.v("TIMING_WAIT",[]);if(!a&&e.length)for(var f=0,k=e.length;f<k;++f)if(!(e[f]in d)){c=!1;break}(c||b)&&ye(b)}};
ve=function(a){if(g.v("DEBUG_CSI_DATA")){var b=g.p("yt.timing.csiData");b||(b=[],g.m("yt.timing.csiData",b,void 0));b.push({page:window.location.href,time:new Date,args:a})}g.v("EXP_DEFER_CSI_PING")&&(g.Db(g.p("yt.timing.deferredPingTimer_")),g.m("yt.timing.deferredPingArgs_",null,void 0));var c="https:"==window.location.protocol?"https://gg.google.com/csi":"http://csi.gstatic.com/csi",c=g.v("CSI_LOG_WITH_YT")?"/csi_204":c,b="",d;for(d in a)b+="&"+d+"="+a[d];a=c+"?"+b.substring(1);b=g.v("DOUBLE_LOG_CSI")?
"/csi_204?"+b.substring(1):null;window.navigator&&window.navigator.sendBeacon?(g.Zd(a),b&&g.Zd(b)):(g.Yd(a),b&&g.Yd(b));g.m("yt.timing.pingSent_",!0,void 0)};
xe=function(a){if(g.v("EXP_DEFER_CSI_PING")){var b=g.p("yt.timing.deferredPingArgs_");b&&(a&&(b.yt_fss=a),ve(b))}};
ie=function(a){return je(a).tick};
ne=function(a){return je(a).info};
je=function(a){return g.p("ytcsi."+(a||"")+"data_")||pe(a)};
pe=function(a){var b={tick:{},span:{},info:{}};g.m("ytcsi."+(a||"")+"data_",b,void 0);return b};
ze=function(a){g.p("yt.timing.pingSent_")||(g.me("aa"),ne(void 0).ap=1,ne(void 0).yt_fss=a,ye())};
g.Ae=function(a,b){g.Yd("/gen_204?"+a,b)};
g.Be=function(a){if(a.classList)return a.classList;a=a.className;return g.ka(a)&&a.match(/\S+/g)||[]};
g.G=function(a,b){return a.classList?a.classList.contains(b):g.La(g.Be(a),b)};
g.I=function(a,b){a.classList?a.classList.add(b):g.G(a,b)||(a.className+=0<a.className.length?" "+b:b)};
g.J=function(a,b){a.classList?a.classList.remove(b):g.G(a,b)&&(a.className=(0,g.Ce)(g.Be(a),function(a){return a!=b}).join(" "))};
g.De=function(a,b,c){c?g.I(a,b):g.J(a,b)};
g.Ee=function(a){var b=a.cloneNode(!1);"TR"==b.tagName||"SELECT"==b.tagName?(0,g.y)(a.childNodes,function(a){b.appendChild(g.Ee(a))}):b.innerHTML=a.innerHTML;
return b};
g.Fe=function(a){this.type="";this.state=this.source=this.data=this.currentTarget=this.relatedTarget=this.target=null;this.charCode=this.keyCode=0;this.shiftKey=this.ctrlKey=this.altKey=!1;this.rotation=this.clientY=this.clientX=0;this.scale=1;this.changedTouches=this.touches=null;if(a=a||window.event){this.event=a;for(var b in a)b in Raa||(this[b]=a[b]);this.scale=a.scale;this.rotation=a.rotation;(b=a.target||a.srcElement)&&3==b.nodeType&&(b=b.parentNode);this.target=b;if(b=a.relatedTarget)try{b=
b.nodeName?b:null}catch(c){b=null}else"mouseover"==this.type?b=a.fromElement:"mouseout"==this.type&&(b=a.toElement);this.relatedTarget=b;this.clientX=void 0!=a.clientX?a.clientX:a.pageX;this.clientY=void 0!=a.clientY?a.clientY:a.pageY;this.keyCode=a.keyCode?a.keyCode:a.which;this.charCode=a.charCode||("keypress"==this.type?this.keyCode:0);this.altKey=a.altKey;this.ctrlKey=a.ctrlKey;this.shiftKey=a.shiftKey;this.vn=a.pageX;this.wn=a.pageY}};
g.He=function(a,b,c,d){a.addEventListener&&("mouseenter"!=b||"onmouseenter"in window.document?"mouseleave"!=b||"onmouseenter"in window.document?"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"):b="mouseout":b="mouseover");return g.Ua(g.Ge,function(e){return e[0]==a&&e[1]==b&&e[2]==c&&e[4]==!!d})};
g.K=function(a,b,c,d){if(!a||!a.addEventListener&&!a.attachEvent)return"";d=!!d;var e=g.He(a,b,c,d);if(e)return e;var e=++Ie.count+"",f=!("mouseenter"!=b&&"mouseleave"!=b||!a.addEventListener||"onmouseenter"in window.document),k;k=f?function(d){d=new g.Fe(d);if(!g.Xd(d.relatedTarget,function(b){return b==a},!0))return d.currentTarget=a,d.type=b,c.call(a,d)}:function(b){b=new g.Fe(b);
b.currentTarget=a;return c.call(a,b)};
k=Ab(k);a.addEventListener?("mouseenter"==b&&f?b="mouseover":"mouseleave"==b&&f?b="mouseout":"mousewheel"==b&&"MozBoxSizing"in window.document.documentElement.style&&(b="MozMousePixelScroll"),a.addEventListener(b,k,d)):a.attachEvent("on"+b,k);g.Ge[e]=[a,b,c,k,d];return e};
g.Je=function(a){a&&("string"==typeof a&&(a=[a]),(0,g.y)(a,function(a){if(a in g.Ge){var c=g.Ge[a],d=c[0],e=c[1],f=c[3],c=c[4];d.removeEventListener?d.removeEventListener(e,f,c):d.detachEvent&&d.detachEvent("on"+e,f);delete g.Ge[a]}}))};
g.Ke=function(a){a=a||window.event;a.returnValue=!1;a.preventDefault&&a.preventDefault()};
g.Me=function(){if(null==g.p("_lact",window)){var a=(0,window.parseInt)(g.v("LACT"),10),a=(0,window.isFinite)(a)?(0,g.F)()-Math.max(a,0):-1;g.m("_lact",a,window);-1==a&&Le();g.K(window.document,"keydown",Le);g.K(window.document,"keyup",Le);g.K(window.document,"mousedown",Le);g.K(window.document,"mouseup",Le);g.x("page-mouse",Le);g.x("page-scroll",Le);g.x("page-resize",Le)}};
Le=function(){null==g.p("_lact",window)&&(g.Me(),g.p("_lact",window));var a=(0,g.F)();g.m("_lact",a,window);g.z("USER_ACTIVE")};
g.Ne=function(){var a=g.p("_lact",window);return null==a?-1:Math.max((0,g.F)()-a,0)};
Oe=function(a){a=a||{};this.url=a.url||"";this.urlV9As2=a.url_v9as2||"";this.args=a.args||g.Ya(Saa);this.assets=a.assets||{};this.attrs=a.attrs||g.Ya(Taa);this.params=a.params||g.Ya(Uaa);this.minVersion=a.min_version||"8.0.0";this.fallback=a.fallback||null;this.fallbackMessage=a.fallbackMessage||null;this.html5=!!a.html5;this.disable=a.disable||{};this.loaded=!!a.loaded;this.messages=a.messages||{}};
g.Pe=function(a){a instanceof Oe||(a=new Oe(a));return a};
Re=function(){return null!=g.Qe};
g.Se=function(){return g.Qe?g.Qe.invoke():null};
Te=function(){return(0,window.parseInt)(g.v("DCLKSTAT",0),10)};
g.Ue=function(a){this.A=a||{cookie:""}};
g.We=function(a){a=(a.A.cookie||"").split(g.Ve);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,values:c}};
g.Ye=function(a,b,c,d){g.Xe.set(""+a,b,c,"/",d||"youtube.com")};
g.af=function(a,b,c){var d=g.v("VALID_SESSION_TEMPDATA_DOMAINS",[]),e=g.Qc(window.location.href);e&&d.push(e);e=g.Qc(a);if(g.La(d,e)||!e&&g.ta(a,"/"))if(a=g.Rc(a),a=g.Sc(a))c?(c=(0,window.parseInt)(c,10),(0,window.isFinite)(c)&&0<c&&(Ze(a,b,c),$e(b))):(Ze(a,b),$e(b))};
Ze=function(a,b,c){var d=g.v("ST_BASE36",!0),e;e=g.v("ST_SHORT",!0)?"ST-":"s_tempdata-";a=e=d?e+g.Ea(a).toString(36):e+g.Ea(a);c=c||5;b=b?g.Wc(b):"";g.Ye(a,b,c)};
$e=function(a){if(a){a=a.itct||a.ved;var b=g.p("yt.logging.screenreporter.storeParentElement");a&&b&&b(new g.md(a))}};
g.bf=function(a,b,c){c=c||"";g.Cc(window.location,g.Xc(a,b||{})+c)};
g.cf=function(a,b){b&&g.af(a,b);(window.ytspf||{}).enabled?window.spf.navigate(a):g.bf(a)};
g.df=function(a,b,c){var d=g.v("EVENT_ID");d&&(b||(b={}),b.ei||(b.ei=d));b&&g.af(a,b);if(c)return!1;g.cf(a);return!0};
g.gf=function(){return g.Pd?"Webkit":g.ef?"Moz":g.E?"ms":g.ff?"O":null};
g.hf=function(){return g.Pd?"-webkit":g.ef?"-moz":g.E?"-ms":g.ff?"-o":null};
g.jf=function(a,b,c,d){this.top=a;this.right=b;this.bottom=c;this.left=d};
g.kf=function(a,b){return a&&b?b instanceof g.jf?b.left>=a.left&&b.right<=a.right&&b.top>=a.top&&b.bottom<=a.bottom:b.x>=a.left&&b.x<=a.right&&b.y>=a.top&&b.y<=a.bottom:!1};
g.lf=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};
g.nf=function(a,b){var c=mf[b];if(!c){var d=Fa(b),c=d;void 0===a.style[d]&&(d=g.gf()+g.Ga(d),void 0!==a.style[d]&&(c=d));mf[b]=c}return c};
g.of=function(a,b){var c=a.style[Fa(b)];return"undefined"!==typeof c?c:a.style[g.nf(a,b)]||""};
g.pf=function(a,b){"number"==typeof a&&(a=(b?Math.round(a):a)+"px");return a};
g.qf=function(a,b){a.style.height=g.pf(b,!0)};
g.rf=function(a,b){a.style.width=g.pf(b,!0)};
g.sf=function(a,b){a.style.display=b?"":"none"};
g.uf=function(){var a=g.Xe.get("PREF",void 0);if(a)for(var a=(0,window.unescape)(a).split("&"),b=0;b<a.length;b++){var c=a[b].split("="),d=c[0];(c=c[1])&&(g.tf[d]=c.toString())}};
vf=function(a){if(/^f([1-9][0-9]*)$/.test(a))throw"ExpectedRegexMatch: "+a;};
wf=function(a){if(!/^\w+$/.test(a))throw"ExpectedRegexMismatch: "+a;};
g.xf=function(a){a=void 0!==g.tf[a]?g.tf[a].toString():null;return null!=a&&/^[A-Fa-f0-9]+$/.test(a)?(0,window.parseInt)(a,16):null};
g.yf=function(a,b){return!!((g.xf("f"+(Math.floor(b/31)+1))||0)&1<<b%31)};
g.zf=function(a,b){(a=g.C(a))&&a.style&&(g.sf(a,b),g.De(a,"hid",!b))};
g.Af=function(a){return(a=g.C(a))?!("none"==a.style.display||g.G(a,"hid")):!1};
Vaa=function(a){if(a=g.C(a))g.Af(a)?(g.sf(a,!1),g.I(a,"hid")):(g.sf(a,!0),g.J(a,"hid"))};
g.L=function(a){(0,g.y)(arguments,function(a){!g.ia(a)||a instanceof window.Element?g.zf(a,!0):(0,g.y)(a,function(a){g.L(a)})})};
g.M=function(a){(0,g.y)(arguments,function(a){!g.ia(a)||a instanceof window.Element?g.zf(a,!1):(0,g.y)(a,function(a){g.M(a)})})};
g.Bf=function(a){(0,g.y)(arguments,function(a){g.ia(a)?(0,g.y)(a,function(a){g.Bf(a)}):Vaa(a)})};
g.Df=function(){this.A=this.minor=this.major=0;this.C="";var a=g.p("window.navigator.plugins"),b=g.p("window.navigator.mimeTypes"),a=a&&a["Shockwave Flash"],b=b&&b["application/x-shockwave-flash"],b=a&&b&&b.enabledPlugin&&a.description||"";if(a=b){var c=a.indexOf("Shockwave Flash");0<=c&&(a=a.substr(c+15));for(var c=a.split(" "),d="",a="",e=0,f=c.length;e<f;e++)if(d)if(a)break;else a=c[e];else d=c[e];d=d.split(".");c=(0,window.parseInt)(d[0],10)||0;d=(0,window.parseInt)(d[1],10)||0;e=0;if("r"==a.charAt(0)||
"d"==a.charAt(0))e=(0,window.parseInt)(a.substr(1),10)||0;a=[c,d,e]}else a=[0,0,0];this.C=b;b=a;this.major=b[0];this.minor=b[1];this.A=b[2];if(0>=this.major){var k,l,n,u;if(g.Cf)try{k=new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(w){k=null}else n=window.document.body,u=window.document.createElement("object"),u.setAttribute("type","application/x-shockwave-flash"),k=n.appendChild(u);if(k&&"GetVariable"in k)try{l=k.GetVariable("$version")}catch(w){l=""}n&&u&&n.removeChild(u);(k=l||
"")?(k=k.split(" ")[1].split(","),k=[(0,window.parseInt)(k[0],10)||0,(0,window.parseInt)(k[1],10)||0,(0,window.parseInt)(k[2],10)||0]):k=[0,0,0];this.major=k[0];this.minor=k[1];this.A=k[2]}};
Ef=function(a,b,c,d){b="string"==typeof b?b.split("."):[b,c,d];b[0]=(0,window.parseInt)(b[0],10)||0;b[1]=(0,window.parseInt)(b[1],10)||0;b[2]=(0,window.parseInt)(b[2],10)||0;return a.major>b[0]||a.major==b[0]&&a.minor>b[1]||a.major==b[0]&&a.minor==b[1]&&a.A>=b[2]};
Ff=function(a){return-1<a.C.indexOf("Gnash")&&-1==a.C.indexOf("AVM2")||9==a.major&&1==a.minor||9==a.major&&0==a.minor&&1==a.A?!1:9<=a.major};
Waa=function(a){return g.Gf?!Ef(a,11,2):g.Hf?!Ef(a,11,3):!Ff(a)};
If=function(a,b,c){if(b){a=g.ka(a)?g.Gd(a):a;var d=g.Ya(c.attrs);d.tabindex=0;var e=g.Ya(c.params);e.flashvars=g.Wc(c.args);if(g.Cf){d.classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000";e.movie=b;b=window.document.createElement("object");for(var f in d)b.setAttribute(f,d[f]);for(f in e)d=window.document.createElement("param"),d.setAttribute("name",f),d.setAttribute("value",e[f]),b.appendChild(d)}else{d.type="application/x-shockwave-flash";d.src=b;b=window.document.createElement("embed");b.setAttribute("name",
d.id);for(f in d)b.setAttribute(f,d[f]);for(f in e)b.setAttribute(f,e[f])}e=window.document.createElement("div");e.appendChild(b);a.innerHTML=e.innerHTML}};
g.Lf=function(a,b){a=g.ka(a)?g.Gd(a):a;b=g.Pe(b);if(window!=window.top){var c=null;window.document.referrer&&(c=window.document.referrer.substring(0,128));b.args.framer=c}c=g.Df.getInstance();Ef(c,b.minVersion)?(c=Jf(b,c),If(a,c,b)):Kf(a,b,c)};
Mf=function(a,b,c){if(a&&a.attrs&&a.attrs.id){a=g.Pe(a);var d=!!b,e=g.C(a.attrs.id),f=e?e.parentNode:null;if(e&&f){if(window!=window.top){var k=null;if(window.document.referrer){var l=window.document.referrer.substring(0,128);waa(l)||(k=l)}else k="unknown";k&&(d=!0,a.args.framer=k)}k=g.Df.getInstance();if(Ef(k,a.minVersion)){var l=Jf(a,k),n="";-1<window.navigator.userAgent.indexOf("Sony/COM2")||(n=e.getAttribute("src")||e.movie);(n!=l||d)&&If(f,l,a);Waa(k)&&Xaa()}else Kf(f,a,k);c&&c()}else g.Bb(function(){Mf(a,
b,c)},50)}};
Kf=function(a,b,c){0==c.major&&b.fallback?b.fallback():0==c.major&&b.fallbackMessage?b.fallbackMessage():a.innerHTML='<div id="flash-upgrade">'+g.Ib("FLASH_UPGRADE",void 0,'You need to upgrade your Adobe Flash Player to watchthis video. <br> <a href="http://get.adobe.com/flashplayer/">Download it from Adobe.</a>')+"</div>"};
Jf=function(a,b){var c;(c=Ff(b)&&a.url)||(c=(-1<window.navigator.userAgent.indexOf("Sony/COM2")&&!Ef(b,9,1,58)?!1:!0)&&a.urlV9As2);return c||a.url};
Xaa=function(){var a=g.C("flash10-promo-div"),b=g.yf(g.uf.getInstance(),107);a&&!b&&g.L(a)};
g.Nf=function(a,b){var c=a.match(Yaa);window.spf.style.load(a,c?c[1]:"",b)};
g.Of=function(a){g.sb.call(this);this.A=[];this.C=a||this};
Pf=function(a,b,c,d){d=Ab((0,g.q)(d,a.C));b.addEventListener(c,d);a.A.push({target:b,name:c,Yb:d})};
Qf=function(a){for(;a.A.length;){var b=a.A.pop();b.target.removeEventListener(b.name,b.Yb)}};
Tf=function(a,b){g.sb.call(this);this.O=this.D=a;this.ia=b;this.L=!1;this.api={};this.Ra=this.V=null;this.Y=new g.wb;g.vb(this,this.Y);this.B={};this.F=this.Za=this.C=this.sb=this.A=null;this.aa=!1;this.W=this.G=this.M=this.T=null;this.$a={};this.kc=["onReady"];this.ga=new g.Of(this);g.vb(this,this.ga);this.Cb=null;this.Lb=window.NaN;this.na={};Rf(this);this.pe("onDetailedError",(0,g.q)(this.DI,this));this.pe("onTabOrderChange",(0,g.q)(this.oy,this));this.pe("onTabAnnounce",(0,g.q)(this.hp,this));
this.pe("WATCH_LATER_VIDEO_ADDED",(0,g.q)(this.GI,this));this.pe("WATCH_LATER_VIDEO_REMOVED",(0,g.q)(this.HI,this));g.Sf||(this.pe("onMouseWheelCapture",(0,g.q)(this.nI,this)),this.pe("onMouseWheelRelease",(0,g.q)(this.oI,this)));this.pe("onAdAnnounce",(0,g.q)(this.hp,this));this.H=new g.Of(this);g.vb(this,this.H);this.ib=!1;this.cb=null};
Vf=function(a,b){a.sb=b;a.A=b.clone();a.C=a.A.attrs.id||a.C;"video-player"==a.C&&(a.C=a.ia,a.A.attrs.id=a.ia);a.O.id==a.C&&(a.C+="-player",a.A.attrs.id=a.C);a.A.args.enablejsapi="1";a.A.args.playerapiid=a.ia;a.Za||(a.Za=Uf(a,a.A.args.jsapicallback||"onYouTubePlayerReady"));a.A.args.jsapicallback=null;var c=a.A.attrs.width;c&&g.rf(a.O,Number(c)||c);(c=a.A.attrs.height)&&g.qf(a.O,Number(c)||c)};
Wf=function(a){a.A.loaded||(a.A.loaded=!0,"0"!=a.A.args.autoplay?a.api.loadVideoByPlayerVars(a.A.args):a.api.cueVideoByPlayerVars(a.A.args))};
Xf=function(a){if(!g.ca(a.A.disable.flash)){var b=a.A.disable,c;c=Ef(g.Df.getInstance(),a.A.minVersion);b.flash=!c}return!a.A.disable.flash};
$f=function(a,b){if((!b||(5!=(Zaa[b.errorCode]||5)?0:-1!=$aa.indexOf(b.errorCode)))&&Xf(a)){var c=Yf(a);c&&c.stopVideo&&c.stopVideo();var d=a.A;c&&c.getUpdatedConfigurationData&&(c=c.getUpdatedConfigurationData(),d=g.Pe(c));d.args.autoplay=1;d.args.html5_unavailable="1";Vf(a,d);Zf(a,"flash")}};
Zf=function(a,b){if(!a.isDisposed()){if(!b){var c;if(!(c=!a.A.html5&&Xf(a))){if(!g.ca(a.A.disable.html5)){var d;c=!0;void 0!=a.A.args.deviceHasDisplay&&(c=a.A.args.deviceHasDisplay);if(2.2==ag)d=!0;else{a:{var e=c;c=g.p("yt.player.utils.videoElement_");c||(c=window.document.createElement("video"),g.m("yt.player.utils.videoElement_",c,void 0));try{if(c.canPlayType)for(var e=e?aba:bba,f=0;f<e.length;f++)if(c.canPlayType(e[f])){d=null;break a}d="fmt.noneavailable"}catch(k){d="html5.missingapi"}}d=!d}d&&
(d=bg(a)||a.A.assets.js);a.A.disable.html5=!d;d||(a.A.args.html5_unavailable="1")}c=!!a.A.disable.html5}b=c?Xf(a)?"flash":"unsupported":"html5"}("flash"==b?a.wO:"html5"==b?a.xO:a.yO).call(a)}};
bg=function(a){var b=!0,c=Yf(a);c&&a.A&&(a=a.A,b=g.A(c,"version")==a.assets.js);return b&&!!g.p("yt.player.Application.create")};
Yf=function(a){var b=g.C(a.C);!b&&a.O&&a.O.querySelector&&(b=a.O.querySelector("#"+a.C));return b};
cg=function(a,b,c){var d=b[c];return function(){try{return a.Cb=null,d.apply(b,arguments)}catch(e){"Bad NPObject as private data!"!=e.message&&"sendAbandonmentPing"!=c&&(e.message+=" ("+c+")",a.Cb=e,g.Fb(e,"WARNING"))}}};
Rf=function(a){a.L=!1;if(a.Ra)for(var b in a.B)a.Ra(b,a.B[b]);for(var c in a.na)g.Db((0,window.parseInt)(c,10));a.na={};a.V=null;a.Ra=null;for(var d in a.api)a.api[d]=null;a.api.addEventListener=(0,g.q)(a.pe,a);a.api.removeEventListener=(0,g.q)(a.CM,a);a.api.destroy=(0,g.q)(a.dispose,a);a.api.getLastError=(0,g.q)(a.Mz,a);a.api.getPlayerType=(0,g.q)(a.aA,a);a.api.getCurrentVideoConfig=(0,g.q)(a.kz,a);a.api.loadNewVideoConfig=(0,g.q)(a.Fo,a);a.api.isReady=(0,g.q)(a.MO,a)};
Uf=function(a,b){var c=b;if("string"==typeof b){if(a.$a[b])return a.$a[b];c=function(){var a=g.p(b);a&&a.apply(g.da,arguments)};
a.$a[b]=c}return c?c:null};
cba=function(a,b){var c="ytPlayer"+b+a.ia;a.B[b]=c;g.da[c]=function(c){var e=g.Bb(function(){a.isDisposed()||(a.Y.la(b,c),g.Wa(a.na,String(e)))},0);
g.Xa(a.na,String(e),!0)};
return c};
dg=function(a){return(a=Yf(a))?"div"==a.tagName.toLowerCase()?"html5":"flash":null};
eg=function(a){g.me("dcp");a.cancel();Rf(a);a.F=null;a.A&&(a.A.loaded=!1);var b=Yf(a);"html5"==dg(a)?a.M=b:b&&b.destroy&&b.destroy();g.Td(a.D);Qf(a.ga);a.G=null;a.W=null};
g.hg=function(a,b){a=g.ka(a)?g.Gd(a):a;b=g.Pe(b);var c=g.fg+"_"+g.qa(a),d=g.gg[c];if(d)return d.Fo(b),d.api;d=new Tf(a,c);g.gg[c]=d;g.z("player-added",d.api);g.tb(d,g.r(dba,d));g.Bb(function(){d.Fo(b)},0);
return d.api};
dba=function(a){g.gg[a.getId()]=null};
g.ig=function(a){a=g.C(a);if(!a)return null;var b=g.fg+"_"+g.qa(a),c=g.gg[b];c||(c=new Tf(a,b),g.gg[b]=c);return c.api};
g.jg=function(){return g.G(g.C("page-container"),"remote-connected")};
eba=function(){g.m("yt.abuse.botguardInitialized",Re,void 0);g.m("yt.abuse.invokeBotguard",g.Se,void 0);g.m("yt.abuse.dclkstatus.checkDclkStatus",Te,void 0);g.m("yt.player.exports.navigate",g.df,void 0);g.m("yt.player.embed",g.hg,void 0);g.m("yt.player.getPlayerByElement",g.ig,void 0);g.m("yt.util.activity.init",g.Me,void 0);g.m("yt.util.activity.getTimeSinceActive",g.Ne,void 0);g.m("yt.util.activity.setTimestamp",Le,void 0);var a=g.p("ytplayer.config");kg(a);g.p("ytspf.enabled")&&(lg=g.Cb(mg,5E3),
(a=g.ng())?(a.addEventListener("onReady",mg),a.addEventListener("onStateChange",mg)):og("unable to init PP monitor"))};
kg=function(a){for(var b in g.gg){var c=g.gg[b];c&&c.cancel()}if(a=a||null){b=g.ng();var d=!0,c=g.pg;g.pg=null;b&&b.getVideoData&&c&&(d=b.getVideoData(),d=!!c.fullscreen||d.video_id!=a.args.video_id||d.list!=a.args.list||d.video_id!=c.videoId||d.list!=c.listId);d?(qg="",g.hg("player-api",a)):b.playVideo();a=g.Pe(a);a.loaded=!0}mg();g.m("ytplayer.config",a,void 0)};
g.ng=function(){var a=g.p("yt.player.getPlayerByElement");return a?a("player-api"):null};
mg=function(){var a=g.ng();if(a){var b;b=g.C("player");b=!b||g.G(b,"off-screen");var c=1==(a&&a.isReady()?a.getPlayerState():void 0),d="watch"==g.v("PAGE_NAME"),e=g.jg();!c||d||e||(og("PP playing off watch (paused)"),a.pauseVideo());b&&d?og("PP off-screen on watch"):b||d||og("PP !off-screen off watch")}};
og=function(a){var b=g.v("PAGE_NAME");b&&(b=[b,qg,g.p("_spf_state.nav-counter")],a+="("+b.join(",")+")",g.m("yt.www.persistentplayer.issue",a,void 0),g.Fb(Error(a),"WARNING"))};
g.rg=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};
g.sg=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};
g.ug=function(a,b){this.A=0;this.L=void 0;this.D=this.C=this.B=null;this.F=this.G=!1;if(a!=g.ea)try{var c=this;a.call(b,function(a){g.tg(c,2,a)},function(a){g.tg(c,3,a)})}catch(d){g.tg(this,3,d)}};
vg=function(){this.next=this.context=this.C=this.D=this.A=null;this.B=!1};
g.xg=function(a,b,c){var d=wg.get();d.D=a;d.C=b;d.context=c;return d};
fba=function(a,b,c){yg(a,b,c,null)||pb(g.r(b,a))};
g.zg=function(a){return new g.ug(function(b,c){var d=a.length,e=[];if(d)for(var f=function(a,c){d--;e[a]=c;0==d&&b(e)},k=function(a){c(a)},l=0,n;l<a.length;l++)n=a[l],fba(n,g.r(f,l),k);
else b(e)})};
Ag=function(a,b){if(0==a.A)if(a.B){var c=a.B;if(c.C){for(var d=0,e=null,f=null,k=c.C;k&&(k.B||(d++,k.A==a&&(e=k),!(e&&1<d)));k=k.next)e||(f=k);e&&(0==c.A&&1==d?Ag(c,b):(f?(d=f,d.next==c.D&&(c.D=d),d.next=d.next.next):Bg(c),Cg(c,e,3,b)))}a.B=null}else g.tg(a,3,b)};
g.Eg=function(a,b){a.C||2!=a.A&&3!=a.A||Dg(a);a.D?a.D.next=b:a.C=b;a.D=b};
g.Gg=function(a,b,c,d){var e=g.xg(null,null,null);e.A=new g.ug(function(a,k){e.D=b?function(c){try{var e=b.call(d,c);a(e)}catch(u){k(u)}}:a;
e.C=c?function(b){try{var e=c.call(d,b);!g.ca(e)&&b instanceof Fg?k(b):a(e)}catch(u){k(u)}}:k});
e.A.B=a;g.Eg(a,e);return e.A};
g.tg=function(a,b,c){0==a.A&&(a==c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.A=1,yg(c,a.W,a.H,a)||(a.L=c,a.A=b,a.B=null,Dg(a),3!=b||c instanceof Fg||gba(a,c)))};
yg=function(a,b,c,d){if(a instanceof g.ug)return g.Eg(a,g.xg(b||g.ea,c||null,d)),!0;if(g.sg(a))return a.then(b,c,d),!0;if(g.oa(a))try{var e=a.then;if(g.na(e))return hba(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1};
hba=function(a,b,c,d,e){function f(a){l||(l=!0,d.call(e,a))}
function k(a){l||(l=!0,c.call(e,a))}
var l=!1;try{b.call(a,k,f)}catch(n){f(n)}};
Dg=function(a){a.G||(a.G=!0,pb(a.O,a))};
Bg=function(a){var b=null;a.C&&(b=a.C,a.C=b.next,b.next=null);a.C||(a.D=null);return b};
Cg=function(a,b,c,d){if(3==c&&b.C&&!b.B)for(;a&&a.F;a=a.B)a.F=!1;if(b.A)b.A.B=null,Hg(b,c,d);else try{b.B?b.D.call(b.context):Hg(b,c,d)}catch(e){Ig.call(null,e)}gb(wg,b)};
Hg=function(a,b,c){2==b?a.D.call(a.context,c):a.C&&a.C.call(a.context,c)};
gba=function(a,b){a.F=!0;pb(function(){a.F&&Ig.call(null,b)})};
Fg=function(a){g.sa.call(this,a)};
kba=function(){var a=g.Ld(),a=new g.lf(0,0,a.width,a.height);g.me("vpc");for(var b=window.document.querySelector(".yt-lockup-thumbnail img[data-ytimg]"),c=b.length,d=[],e=!0,f=0;f<c;f++){var k=b[f],l=k.getBoundingClientRect(),l=new g.lf(l.top,l.left,l.width,l.height);a.left<=l.left+l.width&&l.left<=a.left+a.width&&a.top<=l.top+l.height&&l.top<=a.top+a.height&&(d.push(iba(k)),k.loadTime||(e=!1))}e&&(ne(void 0).yt_eil=1);return g.zg(d).then(jba)};
jba=function(a){return Math.max(Math.max.apply(null,a),0)};
iba=function(a){return new g.ug(function(b){if(a.loadTime)b((0,window.parseInt)(a.loadTime,10));else{var c=g.K(a,"load",function(){if(a.loadTime){var d=(0,window.parseInt)(a.loadTime,10);g.Je(c);b(d)}});
Jg.push(c)}})};
Lg=function(){g.me("ol");g.v("CSI_TICK_PAINT_TIME")?window.requestAnimationFrame&&!window.document.hidden?window.requestAnimationFrame(function(){(0,window.setTimeout)(function(){g.me("cpt");Kg()},0)}):window.document.hidden?(g.me("cpt"),Kg()):(0,window.setTimeout)(function(){g.me("cpt");
Kg()},0):Kg();
g.v("CSI_VIEWPORT")&&kba().then(function(a){g.me("vpl",a)})};
Kg=function(){Mg("init");var a=g.v("PAGE_NAME",void 0);a&&Mg("init-"+a)};
Mg=function(a){g.Qb()?Ng.push(g.Rb(g.r(g.Pb,a),0)):g.z(a)};
Og=function(){g.Ub(Ng);Ng.length=0;g.Je(Jg);Jg.length=0;var a=g.v("PAGE_NAME",void 0);a&&g.Pb("dispose-"+a);g.Pb("dispose")};
lba=function(){Lg()};
mba=function(){g.v("TIMING_REPORT_ON_UNLOAD")&&le(!0);ze("u");xe("u");Og();g.Pb("pageunload")};
Pg=function(){Le()};
Qg=function(){window.yt_spf_loaded_history=!0;g.v("EXP_LACT_HISTORY")&&Le()};
Vg=function(){Rg=1;Sg=Tg=0;g.v("TIMING_REPORT_ON_UNLOAD")&&le(!0);ze("n");xe("n");qe();oe("n");he("mark_navigation_requested");Ug(nba);g.Pb("navigate")};
Zg=function(a){a=a.detail.part||a.detail.partial;g.me("nc"+Tg);++Tg;if(!a.data||!a.data.deferDispose){var b=1==Rg;Rg=2;b?(Ug(oba),Wg()):Ug(pba);if(b=a.data&&a.data.swfcfg)Xg(a.timing,b.args),Yg(b)}};
$g=function(){g.me("np"+Sg);++Sg};
ah=function(a){a=a.detail.response;var b=1==Rg;Rg=3;b&&(Ug(qba),Wg());if(b=a.data&&a.data.swfcfg)Xg(a.timing,b.args),Yg(b)};
dh=function(a){g.me("nd");a=a.detail.response;g.bh=a.cacheKey;a=a.timing;var b=window._spf_state,b=b&&b["nav-counter"]||0;ne(void 0).yt_nav=b;oe("ne",a.responseStart);b=Math.max(0,a.responseStart-a.navigationStart);ne(void 0).srt=b;b=a.spfCached?"hot":"warm";ne(void 0).yt_lt=b;b=+!!a.spfPrefetched;ne(void 0).yt_pft=b;g.me("pfs",a.fetchStart);g.me("pfrs",a.responseStart);"redirectStart"in a&&se(a);Ug(ch);window.document.getElementById("content").style.height="";Lg();Rg=0};
eh=function(a){var b=a.detail.url;if(a=a.detail.err)a.message&&(a.message+=" (url: "+b+")"),g.Fb(a)};
fh=function(a){g.Ae(g.Wc({spfreload:"1",url:a.detail.url,reason:a.detail.reason}))};
sba=function(){rba();g.zb("SERVED_VIA_SPF_HISTORY",!!window.yt_spf_loaded_history);window.yt_spf_loaded_history=!1};
tba=function(){};
Wg=function(){var a=window.document.getElementById("content");-1<a.className.indexOf("spf-animate")&&(a.style.height=a.clientHeight+"px");Og();var a=g.v("TIMING_ACTION"),b;for(b in g.yb)delete g.yb[b];g.zb("PREVIOUS_ACTION",a);g.m("ytplayer.config",null,void 0);if((b=g.ng())&&b.stopVideo){if(b.stopVideo(),b=b.getLastError())qg=b,(b=g.C("movie_player"))&&b.stopVideo?(b.stopVideo(),qg="recovered"):qg="missing2"}else qg="missing";mg()};
Yg=function(a){"cfg"in ie(void 0)||g.me("cfg");kg(a)};
Ug=function(a){var b=window.document.getElementById("progress");b||(b=window.document.createElement("div"),b.id="progress",b.appendChild(window.document.createElement("dt")),b.appendChild(window.document.createElement("dd")),window.document.body.appendChild(b));g.Tb(gh);gh=g.Sb(function(){var c=a[0],d=a[1],e=a[2];b.className="";var f=b.style;f.transitionDuration=f.webkitTransitionDuration=c+"ms";f.width=d+"%";g.Db(hh);hh=g.Bb(function(){b.className=e},c)},0)};
rba=function(){var a=ch[0]+50;g.Db(hh);hh=g.Bb(function(){var a=window.document.getElementById("progress");a&&a.parentNode.removeChild(a)},a)};
Xg=function(a,b){var c=a&&a.spfCached,d=a&&a.spfPrefetched,e=[];c&&!d&&(0,g.y)(uba,function(a){a in b&&(delete b[a],e.push(a))});
g.v("EXP_DEBUG_PREFETCH")&&(e.sort(),c={a:"removeNonCacheableVideoVars",cached:c,prefetched:d,deleted:e.join("")},g.Ae(g.Wc(c)))};
ih=function(){g.Wb.call(this,"www/base");this.B=0};
jh=function(a){(a=a.detail.name)&&$b(a)};
g.aa=[];g.kh=g.kh||{};g.da=this;pa="closure_uid_"+(1E9*Math.random()>>>0);aaa=0;g.F=Date.now||function(){return+new Date};g.ra[" "]=g.ea;g.t(g.sa,Error);g.sa.prototype.name="CustomError";var eaa,faa,gaa,haa,iaa,jaa,daa;g.Ba=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")};
eaa=/&/g;faa=/</g;gaa=/>/g;haa=/"/g;iaa=/'/g;jaa=/\x00/g;daa=/[\x00&<>"']/;g.lh=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
g.vba=2147483648*Math.random()|0;g.Ka=Array.prototype.indexOf?function(a,b,c){return Array.prototype.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;
if(g.ka(a))return g.ka(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};
g.wba=Array.prototype.lastIndexOf?function(a,b,c){return Array.prototype.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;
0>c&&(c=Math.max(0,a.length+c));if(g.ka(a))return g.ka(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
g.y=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};
g.Ce=Array.prototype.filter?function(a,b,c){return Array.prototype.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,k=g.ka(a)?a.split(""):a,l=0;l<d;l++)if(l in k){var n=k[l];
b.call(c,n,l,a)&&(e[f++]=n)}return e};
g.mh=Array.prototype.map?function(a,b,c){return Array.prototype.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=g.ka(a)?a.split(""):a,k=0;k<d;k++)k in f&&(e[k]=b.call(c,f[k],k,a));
return e};
g.nh=Array.prototype.reduce?function(a,b,c,d){d&&(b=(0,g.q)(b,d));return Array.prototype.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;
(0,g.y)(a,function(c,k){e=b.call(d,e,c,k,a)});
return e};
g.oh=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;
return!1};
g.ph=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=g.ka(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;
return!0};g.qh=g.Qa(!1);g.rh=g.Qa(!0);g.sh=g.Qa(null);var Za="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");a:{var th=g.da.navigator;if(th){var uh=th.userAgent;if(uh){g.ab=uh;break a}}g.ab=""};var rb;fb.prototype.get=function(){var a;0<this.C?(this.C--,a=this.A,this.A=a.next,a.next=null):a=this.B();return a};var ob=new fb(function(){return new jb},function(a){a.reset()},100);
ib.prototype.remove=function(){var a=null;this.A&&(a=this.A,this.A=this.A.next,this.A||(this.C=null),a.next=null);return a};
jb.prototype.set=function(a,b){this.ye=a;this.scope=b;this.next=null};
jb.prototype.reset=function(){this.next=this.scope=this.ye=null};var kb,lb=!1,nb=new ib;g.sb.prototype.Td=!1;g.sb.prototype.isDisposed=function(){return this.Td};
g.sb.prototype.dispose=function(){this.Td||(this.Td=!0,this.U())};
g.sb.prototype.U=function(){if(this.Kb)for(;this.Kb.length;)this.Kb.shift()()};g.t(g.wb,g.sb);g.h=g.wb.prototype;g.h.subscribe=function(a,b,c){var d=this.yd[a];d||(d=this.yd[a]=[]);var e=this.D;this.A[e]=a;this.A[e+1]=b;this.A[e+2]=c;this.D=e+3;d.push(e);return e};
g.h.unsubscribe=function(a,b,c){if(a=this.yd[a]){var d=this.A;if(a=g.Ia(a,function(a){return d[a+1]==b&&d[a+2]==c}))return this.zd(a)}return!1};
g.h.zd=function(a){var b=this.A[a];if(b){var c=this.yd[b];0!=this.B?(this.C.push(a),this.A[a+1]=g.ea):(c&&g.Na(c,a),delete this.A[a],delete this.A[a+1],delete this.A[a+2])}return!!b};
g.h.la=function(a,b){var c=this.yd[a];if(c){for(var d=Array(arguments.length-1),e=1,f=arguments.length;e<f;e++)d[e-1]=arguments[e];if(this.F)for(e=0;e<c.length;e++){var k=c[e];maa(this.A[k+1],this.A[k+2],d)}else{this.B++;try{for(e=0,f=c.length;e<f;e++)k=c[e],this.A[k+1].apply(this.A[k+2],d)}finally{if(this.B--,0<this.C.length&&0==this.B)for(;c=this.C.pop();)this.zd(c)}}return 0!=e}return!1};
g.h.clear=function(a){if(a){var b=this.yd[a];b&&((0,g.y)(b,this.zd,this),delete this.yd[a])}else this.A.length=0,this.yd={}};
g.h.qb=g.ba(1);g.h.U=function(){g.wb.K.U.call(this);this.clear();this.C.length=0};var ud;g.yb=window.yt&&window.yt.config_||window.ytcfg&&window.ytcfg.data_||{};g.m("yt.config_",g.yb,void 0);g.m("yt.tokens_",window.yt&&window.yt.tokens_||{},void 0);g.Gb=window.yt&&window.yt.msgs_||g.p("window.ytcfg.msgs")||{};g.m("yt.msgs_",g.Gb,void 0);ud=window.performance&&window.performance.timing&&window.performance.now&&window.__yt_experimental_now?function(){return window.performance.timing.navigationStart+window.performance.now()}:function(){return(new Date).getTime()};
g.Cf="Microsoft Internet Explorer"==window.navigator.appName;var xba=g.p("yt.pubsub.instance_")||new g.wb;g.wb.prototype.subscribe=g.wb.prototype.subscribe;g.wb.prototype.unsubscribeByKey=g.wb.prototype.zd;g.wb.prototype.publish=g.wb.prototype.la;g.wb.prototype.clear=g.wb.prototype.clear;g.m("yt.pubsub.instance_",xba,void 0);var Lb=g.p("yt.pubsub.subscribedKeys_")||{};g.m("yt.pubsub.subscribedKeys_",Lb,void 0);var Nb=g.p("yt.pubsub.topicToKeys_")||{};g.m("yt.pubsub.topicToKeys_",Nb,void 0);var Mb=g.p("yt.pubsub.isSynchronous_")||{};
g.m("yt.pubsub.isSynchronous_",Mb,void 0);var Kb=g.p("yt.pubsub.skipSubId_")||null;g.m("yt.pubsub.skipSubId_",Kb,void 0);g.h=g.Wb.prototype;g.h.PM=function(){this.Vj()||this.init()};
g.h.enable=function(){this.A=1;(0,g.y)("string"==typeof this.page?[this.page]:this.page,function(a){a&&(this.subscribe("init-"+a,this.PM,this),this.subscribe("dispose-"+a,this.dispose,this),g.v("PAGE_NAME")==a&&g.Xb(this))},this)};
g.h.init=function(){g.Tb(this.C);this.A=2;this.G&&this.G()};
g.h.Vj=function(){return 2==this.A};
g.h.dispose=function(){this.A=3;g.Tb(this.C);this.F&&this.F()};
g.h.disable=function(){this.A=4;this.clear();try{this.dispose()}catch(a){g.Fb(a)}};
g.h.subscribe=function(a,b,c){a=g.x(a,b,c);this.D.push(a);return a};
g.h.clear=function(){g.Ob(this.D);this.D=[]};var Yb=g.p("yt.modules.registry_")||{};g.m("yt.modules.registry_",Yb,void 0);var taa={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};g.yba=RegExp("[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.zba=RegExp("^[^\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]*[A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]");g.vh=RegExp("^[^A-Za-z\u00c0-\u00d6\u00d8-\u00f6\u00f8-\u02b8\u0300-\u0590\u0800-\u1fff\u200e\u2c00-\ufb1c\ufe00-\ufe6f\ufefd-\uffff]*[\u0591-\u06ef\u06fa-\u07ff\u200f\ufb1d-\ufdff\ufe70-\ufefc]");cc.prototype.Tf=!0;cc.prototype.Ve=function(){return this.A};
cc.prototype.toString=function(){return"Const{"+this.A+"}"};
var bc={};gc.prototype.Tf=!0;var fc={};gc.prototype.Ve=function(){return this.A};
var paa=ic(""),oaa=/^([-,."'%_!# a-zA-Z0-9]+|(?:rgb|hsl)a?\([0-9.%, ]+\))$/;g.lc.prototype.Tf=!0;g.lc.prototype.Ve=function(){return this.A};
g.lc.prototype.Gm=!0;g.lc.prototype.Bg=function(){return 1};
var qaa=/^(?:(?:https?|mailto|ftp):|[^&:/?#]*(?:[/?#]|$))/i,kc={};g.nc("about:blank");g.qc.prototype.Tf=!0;g.qc.prototype.Ve=function(){return this.A};
g.qc.prototype.Gm=!0;g.qc.prototype.Bg=function(){return 1};
var pc={};var xc,saa,raa,sc;g.tc.prototype.Gm=!0;g.tc.prototype.Bg=function(){return this.C};
g.tc.prototype.Tf=!0;g.tc.prototype.Ve=function(){return this.A};
xc=/^[a-zA-Z0-9-]+$/;saa={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0};raa={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,META:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};sc={};g.Aba=g.vc("<!DOCTYPE html>",0);g.wh=g.vc("",0);g.xh=g.vc("<br>",0);var Fc={};var uaa=/\.vflset|-vfl[a-zA-Z0-9_+=-]+/,vaa=/-[a-zA-Z]{2,3}_[a-zA-Z]{2,3}(?=(\/|$))/;g.Bba=Math.sign||function(a){return 0<a?1:0>a?-1:a};g.yh="StopIteration"in g.da?g.da.StopIteration:{message:"StopIteration",stack:""};g.Cba=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;g.Oc=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;var dd=null;"undefined"!=typeof window.XMLHttpRequest?dd=function(){return new window.XMLHttpRequest}:"undefined"!=typeof window.ActiveXObject&&(dd=function(){return new window.ActiveXObject("Microsoft.XMLHTTP")});var ed={"X-YouTube-Client-Name":"INNERTUBE_CONTEXT_CLIENT_NAME","X-YouTube-Client-Version":"INNERTUBE_CONTEXT_CLIENT_VERSION","X-Youtube-Identity-Token":"XSRF_TOKEN","X-YouTube-Page-CL":"PAGE_CL","X-YouTube-Page-Label":"PAGE_BUILD_LABEL","X-YouTube-Variants-Checksum":"VARIANTS_CHECKSUM"};ld.prototype.C=function(){return{context:g.kd(this.A)}};
ld.prototype.B=function(a,b,c){g.fd("//"+this.A.zO+("/youtubei/"+this.A.innertubeApiVersion+"/"+a)+"?alt=json&key="+this.A.innertubeApiKey,{headers:{"Content-Type":"application/json","X-Goog-Visitor-Id":g.v("VISITOR_DATA")},ea:b,Ju:"JSON",Gc:c.Gc,X:c.X,onError:c.onError,timeout:c.timeout})};var Baa,od;Baa={log_event:"events",log_interaction:"interactions"};g.td={};od={};g.sd=0;g.nd=g.p("yt.logging.transport.logsQueue_")||{};g.m("yt.logging.transport.logsQueue_",g.nd,void 0);g.h=g.xd.prototype;g.h.clone=function(){return new g.xd(this.x,this.y)};
g.h.ceil=function(){this.x=Math.ceil(this.x);this.y=Math.ceil(this.y);return this};
g.h.floor=function(){this.x=Math.floor(this.x);this.y=Math.floor(this.y);return this};
g.h.round=function(){this.x=Math.round(this.x);this.y=Math.round(this.y);return this};
g.h.scale=function(a,b){var c=g.ma(b)?b:a;this.x*=a;this.y*=c;return this};g.h=g.yd.prototype;g.h.clone=function(){return new g.yd(this.width,this.height)};
g.h.area=function(){return this.width*this.height};
g.h.aspectRatio=function(){return this.width/this.height};
g.h.isEmpty=function(){return!this.area()};
g.h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.h.scale=function(a,b){var c=g.ma(b)?b:a;this.width*=a;this.height*=c;return this};var Bh,Ch,Bd,Gh;g.ff=g.bb("Opera");g.E=g.cb();g.zh=g.bb("Edge");g.Ah=g.zh||g.E;g.ef=g.bb("Gecko")&&!(g.za(g.ab.toLowerCase(),"webkit")&&!g.bb("Edge"))&&!(g.bb("Trident")||g.bb("MSIE"))&&!g.bb("Edge");g.Pd=g.za(g.ab.toLowerCase(),"webkit")&&!g.bb("Edge");g.Pd&&g.bb("Mobile");g.Hf=g.bb("Macintosh");g.Gf=g.bb("Windows");g.Dba=g.bb("Linux")||g.bb("CrOS");Bh=g.da.navigator||null;Bh&&g.za(Bh.appVersion||"","X11");g.Eba=g.bb("Android");g.Fba=g.zd();g.Gba=g.bb("iPad");g.Hba=g.bb("iPod");
a:{var Dh="",Eh=function(){var a=g.ab;if(g.ef)return/rv\:([^\);]+)(\)|;)/.exec(a);if(g.zh)return/Edge\/([\d\.]+)/.exec(a);if(g.E)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(g.Pd)return/WebKit\/(\S+)/.exec(a);if(g.ff)return/(?:Version)[ \/]?(\S+)/.exec(a)}();
Eh&&(Dh=Eh?Eh[1]:"");if(g.E){var Fh=Ad();if(null!=Fh&&Fh>(0,window.parseFloat)(Dh)){Ch=String(Fh);break a}}Ch=Dh}g.Cd=Ch;Bd={};Gh=g.da.document;g.Ed=Gh&&g.E?Ad()||("CSS1Compat"==Gh.compatMode?(0,window.parseInt)(g.Cd,10):5):void 0;var Caa;Caa=!g.E||g.Fd(9);g.Iba=!g.ef&&!g.E||g.E&&g.Fd(9)||g.ef&&g.Dd("1.9.1");g.Hh=g.E&&!g.Dd("9");g.Jba=g.E||g.ff||g.Pd;g.Kba=g.E&&!g.Fd(9);var Id={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};g.Sf=g.bb("Firefox");g.Ih=g.zd()||g.bb("iPod");g.Jh=g.bb("iPad");g.Lba=g.bb("Android")&&!(g.db()||g.bb("Firefox")||g.bb("Opera")||g.bb("Silk"));g.Kh=g.db();g.Lh=g.bb("Safari")&&!(g.db()||g.bb("Coast")||g.bb("Opera")||g.bb("Edge")||g.bb("Silk")||g.bb("Android"))&&!(g.zd()||g.bb("iPad")||g.bb("iPod"));var $d={},Haa=0,Mba=g.p("yt.net.ping.workerUrl_")||null;g.m("yt.net.ping.workerUrl_",Mba,void 0);g.ae.prototype.Ub=g.ba(2);g.be.prototype.toString=function(){return this.topic};var Nba=g.p("yt.pubsub2.instance_")||new g.wb;g.wb.prototype.subscribe=g.wb.prototype.subscribe;g.wb.prototype.unsubscribeByKey=g.wb.prototype.zd;g.wb.prototype.publish=g.wb.prototype.la;g.wb.prototype.clear=g.wb.prototype.clear;g.m("yt.pubsub2.instance_",Nba,void 0);g.Mh=g.p("yt.pubsub2.subscribedKeys_")||{};g.m("yt.pubsub2.subscribedKeys_",g.Mh,void 0);g.Nh=g.p("yt.pubsub2.topicToKeys_")||{};g.m("yt.pubsub2.topicToKeys_",g.Nh,void 0);g.Oh=g.p("yt.pubsub2.isAsync_")||{};
g.m("yt.pubsub2.isAsync_",g.Oh,void 0);g.m("yt.pubsub2.skipSubKey_",null,void 0);var ke=(0,g.F)().toString();g.t(ee,g.ae);var Qaa=new g.be("timing-sent",ee);var Iaa=/url\(["']?(http[^'"\)]+)['"]?\)/i;var we={'script[name="scheduler/scheduler"]':"sj",'script[name="player/base"]':"pj",'link[rel="stylesheet"][name="www-player"]':"pc",'script[name="desktop_polymer/desktop_polymer"]':"dpj",'link[rel="import"][name="desktop_polymer"]':"dph",'script[name="mobile_polymer/mobile_polymer"]':"mpj",'link[rel="import"][name="mobile_polymer"]':"mph",'script[name="mobile-polymer-player/mobile-polymer-player"]':"mppj",'link[rel="stylesheet"][name="mobile-polymer-player"]':"mppc"},te=window.performance||window.mozPerformance||
window.msPerformance||window.webkitPerformance||{},Naa=(0,g.q)(te.clearResourceTimings||te.webkitClearResourceTimings||te.mozClearResourceTimings||te.msClearResourceTimings||te.oClearResourceTimings||g.ea,te),he=te.mark?function(a){te.mark(a)}:g.ea;g.Oba=g.Pd?"webkit":g.ef?"moz":g.E?"ms":g.ff?"o":"";g.Ph=g.p("yt.dom.getNextId_");if(!g.Ph){g.Ph=function(){return++Pba};
g.m("yt.dom.getNextId_",g.Ph,void 0);var Pba=0};g.Fe.prototype.preventDefault=function(){this.event&&(this.event.returnValue=!1,this.event.preventDefault&&this.event.preventDefault())};
g.Fe.prototype.stopPropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopPropagation&&this.event.stopPropagation())};
g.Fe.prototype.stopImmediatePropagation=function(){this.event&&(this.event.cancelBubble=!0,this.event.stopImmediatePropagation&&this.event.stopImmediatePropagation())};
var Raa={stopImmediatePropagation:1,stopPropagation:1,preventMouseEvent:1,preventManipulation:1,preventDefault:1,layerX:1,layerY:1,scale:1,rotation:1,webkitMovementX:1,webkitMovementY:1};g.Ge=g.p("yt.events.listeners_")||{};g.m("yt.events.listeners_",g.Ge,void 0);var Ie=g.p("yt.events.counter_")||{count:0};g.m("yt.events.counter_",Ie,void 0);var Saa={enablejsapi:1},Taa={},Uaa={allowscriptaccess:"always",allowfullscreen:"true",bgcolor:"#000000"};Oe.prototype.clone=function(){var a=new Oe,b;for(b in this)if(this.hasOwnProperty(b)){var c=this[b];"object"==g.ga(c)?a[b]=g.Ya(c):a[b]=c}return a};g.Qe=null;g.Ve=/\s*;\s*/;g.h=g.Ue.prototype;g.h.isEnabled=function(){return window.navigator.cookieEnabled};
g.h.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error('Invalid cookie name "'+a+'"');if(/[;\r\n]/.test(b))throw Error('Invalid cookie value "'+b+'"');g.ca(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date((0,g.F)()+1E3*c)).toUTCString();this.A.cookie=a+"="+b+e+d+c+f};
g.h.get=function(a,b){for(var c=a+"=",d=(this.A.cookie||"").split(g.Ve),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};
g.h.remove=function(a,b,c){var d=g.ca(this.get(a));this.set(a,"",0,b,c);return d};
g.h.Ob=g.ba(3);g.h.nb=g.ba(4);g.h.isEmpty=function(){return!this.A.cookie};
g.h.qb=g.ba(0);g.h.xe=g.ba(5);g.h.clear=function(){for(var a=g.We(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])};
g.Xe=new g.Ue("undefined"==typeof window.document?null:window.document);g.Xe.C=3950;g.Qh=g.E?"focusin":"DOMFocusIn";g.Rh=g.E?"focusout":"DOMFocusOut";g.Sh=g.Pd?"webkitTransitionEnd":g.ff?"otransitionend":"transitionend";g.h=g.jf.prototype;g.h.getHeight=function(){return this.bottom-this.top};
g.h.clone=function(){return new g.jf(this.top,this.right,this.bottom,this.left)};
g.h.contains=function(a){return g.kf(this,a)};
g.h.ceil=function(){this.top=Math.ceil(this.top);this.right=Math.ceil(this.right);this.bottom=Math.ceil(this.bottom);this.left=Math.ceil(this.left);return this};
g.h.floor=function(){this.top=Math.floor(this.top);this.right=Math.floor(this.right);this.bottom=Math.floor(this.bottom);this.left=Math.floor(this.left);return this};
g.h.round=function(){this.top=Math.round(this.top);this.right=Math.round(this.right);this.bottom=Math.round(this.bottom);this.left=Math.round(this.left);return this};
g.h.scale=function(a,b){var c=g.ma(b)?b:a;this.left*=a;this.right*=a;this.top*=c;this.bottom*=c;return this};g.h=g.lf.prototype;g.h.clone=function(){return new g.lf(this.left,this.top,this.width,this.height)};
g.h.contains=function(a){return a instanceof g.lf?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};
g.h.ceil=function(){this.left=Math.ceil(this.left);this.top=Math.ceil(this.top);this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.h.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
g.h.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
g.h.scale=function(a,b){var c=g.ma(b)?b:a;this.left*=a;this.width*=a;this.top*=c;this.height*=c;return this};var mf;mf={};g.Th=g.ef?"MozUserSelect":g.Pd||g.zh?"WebkitUserSelect":null;g.fa(g.uf);g.tf=g.p("yt.prefs.UserPrefs.prefs_")||{};g.m("yt.prefs.UserPrefs.prefs_",g.tf,void 0);g.h=g.uf.prototype;g.h.get=function(a,b){wf(a);vf(a);var c=void 0!==g.tf[a]?g.tf[a].toString():null;return null!=c?c:b?b:""};
g.h.set=function(a,b){wf(a);vf(a);if(null==b)throw"ExpectedNotNull";g.tf[a]=b.toString()};
g.h.remove=function(a){wf(a);vf(a);delete g.tf[a]};
g.h.save=function(){var a;a=[];for(var b in g.tf)a.push(b+"="+(0,window.escape)(g.tf[b]));a=a.join("&");g.Ye("PREF",a,63072E3)};
g.h.clear=function(){g.tf={}};g.Uh=g.Ra(function(){if(g.E)return g.Dd("10.0");var a=window.document.createElement("DIV"),b=g.hf(),c={transition:"opacity 1s linear"};b&&(c[b+"-transition"]="opacity 1s linear");g.Bc(a,g.zc("div",{style:c}));return""!=g.of(a.firstChild,"transition")});g.fa(g.Df);g.Df.prototype.getVersion=function(){return[this.major,this.minor,this.A]};var Yaa=/cssbin\/(?:debug-)?([a-zA-Z0-9_-]+?)(?:-2x|-web|-rtl|-vfl|.css)/;var ag;var Vh=g.ab,Vh=Vh.toLowerCase();if(g.za(Vh,"android")){var Wh=Vh.match(/android\D*(\d\.\d)[^\;|\)]*[\;\)]/);if(Wh)ag=Number(Wh[1]);else{var Xh={cupcake:1.5,donut:1.6,eclair:2,froyo:2.2,gingerbread:2.3,honeycomb:3,"ice cream sandwich":4,jellybean:4.1},Yh=Vh.match("("+g.Ta(Xh).join("|")+")");ag=Yh?Xh[Yh[0]]:0}}else ag=void 0;var aba=['video/mp4; codecs="avc1.42001E, mp4a.40.2"','video/webm; codecs="vp8.0, vorbis"'],bba=['audio/mp4; codecs="mp4a.40.2"'];g.t(g.Of,g.sb);g.Of.prototype.Va=g.ba(6);g.Of.prototype.U=function(){Qf(this);g.Of.K.U.call(this)};var Zaa={"api.invalidparam":2,auth:150,"drm.auth":150,heartbeat:150,"html5.unsupportedads":5,"fmt.noneavailable":5,"fmt.decode":5,"fmt.unplayable":5,"html5.missingapi":5,"html5.unsupportedlive":5,"drm.unavailable":5};g.t(Tf,g.sb);var $aa=["drm.unavailable","fmt.noneavailable","html5.missingapi","html5.unsupportedads","html5.unsupportedlive"];g.h=Tf.prototype;g.h.getId=function(){return this.ia};
g.h.Fo=function(a,b){this.isDisposed()||(Vf(this,a),Zf(this,b),this.L&&Wf(this))};
g.h.kz=function(){return this.sb};
g.h.xO=function(){if(!this.aa){var a=bg(this);a&&"html5"==dg(this)?(this.F="html5",this.L||this.Vg()):(eg(this),this.F="html5",a&&this.M?(this.D.appendChild(this.M),this.Vg()):(this.A.loaded=!0,this.T=(0,g.q)(function(){var a=this.D,c=this.A.clone();g.p("yt.player.Application.create")(a,c);this.Vg()},this),this.aa=!0,a?this.T():(g.Hc(this.A.assets.js,this.T),g.Nf(this.A.assets.css))))}};
g.h.wO=function(){var a=this.A.clone();if(!this.G){var b=Yf(this);b&&(this.G=window.document.createElement("span"),this.G.tabIndex=0,Pf(this.ga,this.G,"focus",this.It),this.W=window.document.createElement("span"),this.W.tabIndex=0,Pf(this.ga,this.W,"focus",this.It),g.Ud(this.G,b),g.Vd(this.W,b))}a.attrs.width=a.attrs.width||"100%";a.attrs.height=a.attrs.height||"100%";"flash"==dg(this)?(this.F="flash",this.L||Mf(a,!1,(0,g.q)(this.Vg,this))):(eg(this),this.F="flash",this.A.loaded=!0,g.Lf(this.D,a),
this.Vg())};
g.h.It=function(){Yf(this).focus()};
g.h.Vg=function(){if(!this.isDisposed()){var a=Yf(this),b=!1;try{a&&a.getApiInterface&&a.getApiInterface()&&(b=!0)}catch(f){}if(b)if(this.aa=!1,a.isNotServable&&a.isNotServable(this.A.args.video_id))$f(this);else{Rf(this);this.L=!0;a=Yf(this);a.addEventListener&&(this.V=cg(this,a,"addEventListener"));a.removeEventListener&&(this.Ra=cg(this,a,"removeEventListener"));for(var b=a.getApiInterface(),b=b.concat(a.getInternalApiInterface()),c=0;c<b.length;c++){var d=b[c];this.api[d]||(this.api[d]=cg(this,
a,d))}for(var e in this.B)this.V(e,this.B[e]);Wf(this);this.Za&&this.Za(this.api);this.Y.la("onReady",this.api)}else this.Lb=g.Bb((0,g.q)(this.Vg,this),50)}};
g.h.MO=function(){return this.L};
g.h.pe=function(a,b){if(!this.isDisposed()){var c=Uf(this,b);if(c){if(!g.La(this.kc,a)&&!this.B[a]){var d=cba(this,a);this.V&&this.V(a,d)}this.Y.subscribe(a,c);"onReady"==a&&this.L&&g.Bb(g.r(c,this.api),0)}}};
g.h.CM=function(a,b){if(!this.isDisposed()){var c=Uf(this,b);c&&this.Y.unsubscribe(a,c)}};
g.h.oy=function(a){a=a?Faa:Eaa;for(var b=a(window.document.activeElement);b&&(1!=b.nodeType||b==this.G||b==this.W||(b.focus(),b!=window.document.activeElement));)b=a(b)};
g.h.hp=function(a){g.z("a11y-announce",a)};
g.h.DI=function(a){$f(this,a)};
g.h.GI=function(a){g.z("WATCH_LATER_VIDEO_ADDED",a)};
g.h.HI=function(a){g.z("WATCH_LATER_VIDEO_REMOVED",a)};
g.h.nI=function(){this.ib||(g.Kh?(this.cb=g.Od(window.document),Pf(this.H,window,"scroll",this.LK),Pf(this.H,this.D,"touchmove",this.tK)):(Pf(this.H,this.D,"mousewheel",this.Vt),Pf(this.H,this.D,"wheel",this.Vt)),this.ib=!0)};
g.h.oI=function(){Qf(this.H);this.ib=!1};
g.h.Vt=function(a){g.Ke(a)};
g.h.LK=function(){window.scrollTo(this.cb.x,this.cb.y)};
g.h.tK=function(a){a.preventDefault()};
g.h.yO=function(){eg(this);this.F="unsupported";var a='Adobe Flash Player or an HTML5 supported browser is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/">Get the latest Flash Player</a> <br> <a href="/html5">Learn more about upgrading to an HTML5 browser</a>',b=window.navigator.userAgent.match(/Version\/(\d).*Safari/);b&&5<=(0,window.parseInt)(b[1],10)&&(a='Adobe Flash Player or QuickTime is required for video playback. <br> <a href="http://get.adobe.com/flashplayer/"> Get the latest Flash Player</a> <br> <a href="http://www.apple.com/quicktime/download/">Get the latest version of QuickTime</a>');
b=this.A.messages.player_fallback||a;a=g.C("player-unavailable");g.C("unavailable-submessage")&&a&&(g.C("unavailable-submessage").innerHTML=b,(b=g.D("icon",a))&&g.Ec(b,"icon")&&(b.src=g.A(b,"icon")),g.sf(a,!0),g.I(g.C("player"),"off-screen-trigger"))};
g.h.aA=function(){return this.F||dg(this)};
g.h.Mz=function(){return this.Cb};
g.h.cancel=function(){this.T&&g.Ic(this.A.assets.js,this.T);g.Db(this.Lb);this.aa=!1};
g.h.U=function(){eg(this);if(this.M&&this.A)try{this.M.destroy()}catch(b){g.Fb(b)}this.$a=null;for(var a in this.B)g.da[this.B[a]]=null;this.sb=this.A=this.api=null;delete this.D;delete this.O;Tf.K.U.call(this)};g.gg={};g.fg="player_uid_"+(1E9*Math.random()>>>0);var Qba=g.p("yt.abuse.botguardInitialized")||Re;g.m("yt.abuse.botguardInitialized",Qba,void 0);var Rba=g.p("yt.abuse.invokeBotguard")||g.Se;g.m("yt.abuse.invokeBotguard",Rba,void 0);var Sba=g.p("yt.abuse.dclkstatus.checkDclkStatus")||Te;g.m("yt.abuse.dclkstatus.checkDclkStatus",Sba,void 0);var Tba=g.p("yt.player.exports.navigate")||g.df;g.m("yt.player.exports.navigate",Tba,void 0);var Uba=g.p("yt.player.embed")||g.hg;g.m("yt.player.embed",Uba,void 0);var Vba=g.p("yt.player.getPlayerByElement")||g.ig;
g.m("yt.player.getPlayerByElement",Vba,void 0);var Wba=g.p("yt.util.activity.init")||g.Me;g.m("yt.util.activity.init",Wba,void 0);var Xba=g.p("yt.util.activity.getTimeSinceActive")||g.Ne;g.m("yt.util.activity.getTimeSinceActive",Xba,void 0);var Yba=g.p("yt.util.activity.setTimestamp")||Le;g.m("yt.util.activity.setTimestamp",Yba,void 0);var lg,qg;g.pg=null;qg="";vg.prototype.reset=function(){this.context=this.C=this.D=this.A=null;this.B=!1};
var wg=new fb(function(){return new vg},function(a){a.reset()},100);
g.ug.prototype.then=function(a,b,c){return g.Gg(this,g.na(a)?a:null,g.na(b)?b:null,c)};
g.rg(g.ug);g.ug.prototype.cancel=function(a){0==this.A&&pb(function(){var b=new Fg(a);Ag(this,b)},this)};
g.ug.prototype.W=function(a){this.A=0;g.tg(this,2,a)};
g.ug.prototype.H=function(a){this.A=0;g.tg(this,3,a)};
g.ug.prototype.O=function(){for(var a=null;a=Bg(this);)Cg(this,a,this.A,this.L);this.G=!1};
var Ig=eb;g.t(Fg,g.sa);Fg.prototype.name="cancel";var Jg=[];var Ng=[];var Rg,hh,gh,Tg,Sg,uba,nba,qba,oba,pba,ch;Tg=0;Sg=0;uba=["server_prefetched_vast","vmap"];nba=[900,60,"waiting"];qba=[500,99,"waiting"];oba=[300,60,"waiting"];pba=[400,99,"waiting"];ch=[300,101,"done"];window.yt=window.yt||{};g.m("yt.setConfig",g.zb,void 0);g.m("yt.getConfig",g.v,void 0);g.m("yt.hasMsg",g.Hb,void 0);g.m("yt.pubsub.publish",g.z,void 0);g.m("yt.pubsub.subscribe",g.x,void 0);g.m("yt.setMsg",function(a){xb(g.Gb,arguments)},void 0);
g.m("yt.setGoogMsg",function(a){xb(g.Gb,arguments)},void 0);
g.m("yt.timing.reportAdToVideo",function(a,b,c){c={v:2,s:"youtube",action:c?"watch,ad2video_html5":"watch,ad2video"};a.aft=a.pbs=a.astv||a.actv;var d=[],e;for(e in a)"_"!=e.charAt(0)&&d.push(e+"."+Math.round(a[e]));c.rt=d.join(",");for(var f in b)"_"!=f.charAt(0)&&(c[f]=b[f]);a=g.v("TIMING_INFO",{});"e"in a&&(c.e=a.e);"ei"in a&&(c.ei=a.ei);ve(c)},void 0);
g.m("ytcsi.tick",g.me,void 0);g.t(ih,g.Wb);
ih.prototype.enable=function(){window.onload=lba;window.onunload=mba;window.onerror=naa;var a=window.ytspf||{};a.enabled?(window.addEventListener&&(window.addEventListener("spfclick",Pg),window.addEventListener("spfhistory",Qg),window.addEventListener("spfrequest",Vg),window.addEventListener("spfpartprocess",Zg),window.addEventListener("spfpartdone",$g),window.addEventListener("spfprocess",ah),window.addEventListener("spfdone",dh),window.addEventListener("spferror",eh),window.addEventListener("spfreload",
fh),window.addEventListener("spfjsbeforeunload",jh)),a.config=a.config||{},window.ytdepmap?window.spf.script.ready("spf",function(){a.enabled=window.spf.init(a.config)}):a.enabled=window.spf.init(a.config),this.subscribe("init",sba),this.subscribe("dispose",tba)):window.spf.dispose();
this.subscribe("init",this.init,this);this.subscribe("dispose",this.dispose,this)};
ih.prototype.init=function(){ih.K.init.call(this);(window.ytspf||{}).enabled||window.spf.dispose();var a=window.ytPageFrameLoaded||!1,b,c;!a&&g.v("PAGEFRAME_JS")?(b=g.v("PAGEFRAME_JS",void 0),c=function(){window.ytPageFrameLoaded=!0;g.p("ytbin.www.pageframe.setup")()}):a&&(a=g.p("yt.www.masthead.loadSearchbox"))&&a();
var a=g.v("JS_COMMON_MODULE"),d=g.v("JS_PAGE_MODULES");d||(d=[a]);a=g.v("JS_DELAY_LOAD",0);0<a?(g.Db(this.B),this.B=g.Bb(function(){b&&g.Hc(b,c);window.spf.script.require(d)},a)):(b&&g.Hc(b,c),window.spf.script.require(d));
eba();g.m("yt.timing.ready_",!0,void 0);Oaa();le(!1);var a=!!g.p("yt.reactLoaded"),e=g.v("REACT_JS",void 0);!a&&e&&g.Hc(e,function(){g.m("yt.reactLoaded",!0,void 0)})};
ih.prototype.dispose=function(){g.Db(this.B);var a=g.p("ytbin.www.pageframe.cancelSetup");a&&a();g.Eb(lg);if(a=g.ng())a.removeEventListener("onReady",mg),a.removeEventListener("onStateChange",mg);g.m("yt.timing.ready_",!1,void 0);ih.K.dispose.call(this)};
ih.prototype.disable=function(){ih.K.disable.call(this);window.removeEventListener&&(window.removeEventListener("spfclick",Pg),window.removeEventListener("spfhistory",Qg),window.removeEventListener("spfrequest",Vg),window.removeEventListener("spfpartprocess",Zg),window.removeEventListener("spfpartdone",$g),window.removeEventListener("spfprocess",ah),window.removeEventListener("spfdone",dh),window.removeEventListener("spferror",eh),window.removeEventListener("spfreload",fh),window.removeEventListener("spfjsbeforeunload",
jh));window.onload=null;window.onunload=null;window.onerror=null};
g.ac(new ih);})(_yt_www);
